### ISSUE TITLE
Convert 27 to "AB"

### ISSUE THREAD

**Issue by aidanlister** [burnash/gspread#397] opened 2016-07-06 03:56 UTC
Any helper for this?

**Comment by santiagosanti** [comment] 2016-07-06 05:49
Your request is not clear. What exactly are you trying to do?

**Comment by NotLeet** [comment] 2016-07-06 09:23
There is not. Fortunately writing a function to do this yourself is pretty trivial.

This snippet could use better validation, make fewer assumptions about which python version you're using and probably use a while loop instead of tail recursion. It should be enough to get you started though.

https://gist.github.com/NotLeet/82ce406201ac13d83bd15ec706725583

**Comment by aidanlister** [comment] 2016-07-06 13:17
@NotLeet that'll do, thanks. Seems like it'd be a useful addition to the utils.py file, there's no way I can see to get a range numerically e.g. worksheet.get_range(1,1, 5, 5) .. instead I have to translate the range to do get_range('A1:K5').

**Comment by burnash** [comment] 2016-07-16 23:18
@aidanlister if `range()` could accept integers would it work for your case? See https://github.com/burnash/gspread/pull/142

**Comment by aidanlister** [comment] 2016-07-17 00:47
Yes that'd solve my issue elegantly.

**Comment by aidanlister** [comment] 2016-07-17 00:49
Also I note from your PR that the function I was looking for was ws.get_addr_int(row, col):
https://github.com/burnash/gspread/blob/6d9685890abf5b8844fadd8a40ae9838909ffe2c/gspread/models.py#L264

**Comment by FlorianHoevelmann** [comment] 2016-07-21 14:25
I know this is already fixed but maybe this helps in other cases.

I created a List starting from 'A' to 'Z' and then 'AA' to 'ZZ' etc.
`letter_number_conversion, first, second = [chr(i+65) for i in range(0,26)], [], []
    for a in letter_number_conversion:
        for i in letter_number_conversion:
            first.append(a+i)
            for u in letter_number_conversion:
                second.append(a+i+u)
  first.extend(second)
  letter_number_conversion.extend(first)`
so in your case it would be letter_number_conversion[27].
it also works the other way around letter_number_conversion.index('AB').

**Comment by burnash** [comment] 2016-12-12 22:29
Looks like the issue is resolved. For the record, `Worksheet.range` now accepts integers (#142 is merged).

**Closed by burnash** 2016-12-12 22:29 UTC
