### ISSUE TITLE
network glitch hangs cell write

### ISSUE THREAD

**Issue by schneemaier** [burnash/gspread#189] opened 2014-12-05 12:31 UTC
I am running the following cycle to update a spreadsheet every minute:
```python
   while True:
        try:
            ..... get data
        except:
            ..... error handling if any
        try:
            worksheet = login_open_sheet(GDOCS_EMAIL, GDOCS_PASSWORD, GDOCS_SPREADSHEET_NAME)
        except:
            logging.debug('ERROR')
            worksheet = None
        if worksheet <> None :
            try:
                aa = str(timeStart)
                worksheet.append_row((aa[:19], str(tp[sensors[0]]).replace('.', ','), str(tp[sensors[1]]).replace('.', ','), str(tp[sensors[2]]).replace('.', ','), str(tp[sensors[3]]).replace('.', ','), str(tp$
            except:
                mess = str(sys.exc_info()[0])
                print datetime.datetime.now(), "Worksheet write failed"
                logging.debug(mess)
```

This runs fine, but every day around 1 am, when my ISP resets the network connection it hangs on the line  worksheet.append_row. It seems if the network connection is dropped while the append operation is ongoing the append_row gets into an infinite loop: the cycle is no longer running, but at the same time there is no error message

**Comment by msuozzo** [comment] 2015-10-11 20:21
Duplicate of #302

**Closed by msuozzo** 2015-10-11 20:21 UTC
