### ISSUE TITLE
error 400 after multiple append_row 

### ISSUE THREAD

**Issue by JonRobert** [burnash/gspread#471] opened 2017-07-07 15:35 UTC
I receive an error code 400 periodically with the same code (see attached) while writing data to a google sheet.

I am collecting 50 to 60 sets of readings at a time.   I wait for the credential update then write the data to a google sheet all at one time.  I have reproduced this twice (out of two tries) with this code.  In the last case the program had successfully written ~ 500 rows before this error.  I know I don't need 15 decimal places....just haven't gotten that far.

Is this a bug or should I just wrap the append_row call in a try / exception?

Sorry about the inserted code.  It looks fine in the write tab but wrong in the preview tab. If there is a way fix it please let me know.

Regards
Jon

Code:
`if credentials.access_token_expired:
    print("   credentials expired    ")
    client.login()
    # with credentials renewed we can safely write data Matrix to google
    #
    for i in range (0,n):
        print("i = ", i,"matrix = ", [Matrix[i][0], Matrix[i][1], Matrix[i][2], Matrix[i][3], Matrix[i][4], Matrix[i][5], Matrix[i][6], Matrix[i][7]]   )
        #original: append_row ([Location, data_time, sensor_dataBME[0], sensor_dataBME[1], sensor_dataBME[2], sensor_dataBME[3], sensor_dataCCS[0], sensor_dataCCS[1]])
        wksheet.append_row ([Matrix[i][0], Matrix[i][1], Matrix[i][2], Matrix[i][3], Matrix[i][4], Matrix[i][5], Matrix[i][6], Matrix[i][7]])
    n = 0`

Results:
`i =  1 matrix =  ['bench_top2', '2017-07-07 04:49:26', 23.4299057958552, 1005.9803670969352, 56.842020402747856, 14.798309876404769, 1, 410]
i =  2 matrix =  ['bench_top2', '2017-07-07 04:50:26', 23.434925745713425, 1006.016027158073, 56.831702212980126, 14.80126618830945, 1, 410]
        "
        "
i =  43 matrix =  ['bench_top2', '2017-07-07 05:20:09', 23.384726247131155, 1005.6324267709477, 56.814396554491225, 14.7476055580294, 1, 410]
i =  44 matrix =  ['bench_top2', '2017-07-07 05:21:09', 23.39978609670584, 1005.7123705194266, 56.761537537043935, 14.752093604114625, 2, 414]
i =  45 matrix =  ['bench_top2', '2017-07-07 05:22:10', 23.39476614684761, 1005.6496913287635, 56.74995003639512, 14.744756154126632, 2, 414]  <<--- last line apparing in google sheet.
i =  46 matrix =  ['bench_top2', '2017-07-07 05:23:11', 23.384726247131155, 1005.6324267709477, 56.754157431228634, 14.735557733376883, 2, 414]
Traceback (most recent call last):
  File "logsensor_706o.py", line 148, in <module>
    wksheet.append_row ([Matrix[i][0], Matrix[i][1], Matrix[i][2], Matrix[i][3], Matrix[i][4], Matrix[i][5], Matrix[i][6], Matrix[i][7]])
  File "/usr/local/lib/python3.4/dist-packages/gspread-0.6.2-py3.4.egg/gspread/models.py", line 661, in append_row
  File "/usr/local/lib/python3.4/dist-packages/gspread-0.6.2-py3.4.egg/gspread/models.py", line 584, in update_cells
  File "/usr/local/lib/python3.4/dist-packages/gspread-0.6.2-py3.4.egg/gspread/client.py", line 241, in post_cells
  File "/usr/local/lib/python3.4/dist-packages/gspread-0.6.2-py3.4.egg/gspread/httpsession.py", line 79, in post
  File "/usr/local/lib/python3.4/dist-packages/gspread-0.6.2-py3.4.egg/gspread/httpsession.py", line 69, in request
gspread.exceptions.RequestError: (400, "400: b'Invalid query parameter value for cell_id.'")

`

Operating System: Jessie lite
Python version: 3.4.2
was running in tmux session with me logged out.
gspread version: believe 0.62 (installed early June 2017)

**Comment by synth3tk** [comment] 2017-07-13 17:26
I'm also experiencing this same issue on 0.62, using Python 2.7.5.

**Comment by JonRobert** [comment] 2017-07-13 18:00
I David,

 

I solved it (or at least got around it) by using the following:

 

 

        for i in range (0,n):

                print("i = ", i,"matrix = ", [Matrix[i][0], Matrix[i][1], Matrix[i][2], Matrix[i][3], Matrix[i][4], Matrix[i][5], Matrix[i][6], Matrix[i][7]]   )

                try:

                    wksheet.append_row ([Matrix[i][0], Matrix[i][1], Matrix[i][2], Matrix[i][3], Matrix[i][4], Matrix[i][5], Matrix[i][6], Matrix[i][7]])

                except:

                    print("line 146      except:     append_row error.  i =",i)

                    except_count += 1

                    # retry after 10 seconds.

                    time.sleep (10)

                    wksheet.append_row ([Matrix[i][0], Matrix[i][1], Matrix[i][2], Matrix[i][3], Matrix[i][4], Matrix[i][5], Matrix[i][6], Matrix[i][7]])

 

I’ve tested it for a few days with good results.  Note I am counting the “excepts”.

 

I don’t know if its related but periodically my google sheet has a blank row, no data missing but a blank row.   I cannot correlate the blank rows to the number of excepts counted but I’m suspicious.

BTW the 10 seconds is not a refined number,  my program is not time sensitive so I picked what I though was a safe number.

 

Hope this helps.

 

John

**Comment by synth3tk** [comment] 2017-07-13 18:21
I've also gotten the blank row at the bottom randomly, which throws off my script on the next run. My assumption is it's somehow related. Not sure whether it's a symptom or the cause.

**Comment by burnash** [comment] 2018-03-12 09:24
@JonRobert is the issue still persist? If so, can you try to upgrade to the latest version of the library? I've released a new version that uses Sheets API v4, which natively supports operations like `append_row`. I'm closing the issue for now. Feel free to reopen it if you experience any problems after upgrading.

**Closed by burnash** 2018-03-12 09:24 UTC
