### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by mosesmc52** [burnash/gspread#207] opened 2015-02-20 16:38 UTC
Hi burnash,

For the most part the gspread library works well. However, sometimes I receive this error (Traceback Below). I'm not quite sure the cause, but after rerunning the script the error disappears.  I just wanted to let you know and find a solution to prevent this error from occurring.  

Thanks,

Moses

Traceback (most recent call last):
  File "upload_data.py", line 1299, in <module>
    main()
  File "/Users/mosesmccall/.virtualenvs/variable_extraction/lib/python2.7/site-packages/raven/base.py", line 684, in wrapper
    return func(*funcargs, **funckwargs)
  File "upload_data.py", line 1222, in main
    create_lawfirm_worksheet(wks, documents)
  File "upload_data.py", line 607, in create_lawfirm_worksheet
    sh = wks.add_worksheet(title='%s %s' % ('lawfirms', today ), rows=rows, cols=cols)
  File "/Users/.virtualenvs/variable_extraction/lib/python2.7/site-packages/gspread/models.py", line 91, in add_worksheet
    worksheet = Worksheet(self, elem)
  File "/Users/.virtualenvs/variable_extraction/lib/python2.7/site-packages/gspread/models.py", line 174, in __init__
    self._id = element.find(_ns('id')).text.split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by msuozzo** [comment] 2015-10-15 02:48
Looks like this is a duplicate of #174.

**Closed by msuozzo** 2015-10-15 02:48 UTC
