### ISSUE TITLE
insufficient permission

### ISSUE THREAD

**Issue by drskuce** [burnash/gspread#532] opened 2018-04-05 18:23 UTC
I have followed example from 
https://www.twilio.com/blog/2017/02/an-easy-way-to-read-and-write-to-a-google-spreadsheet-in-python.html
exactly using PyCharm
windows 10 up to date
my account permissions are "administrator"

here is what I get:

Traceback (most recent call last):
  File "C:/Users/doug/PycharmProjects/Memex1/spreadsheet.py", line 12, in <module>
    sheet = client.open("Copy of Legislators 2017a").sheet1
  File "C:\Users\doug\p2venv\lib\site-packages\gspread\v4\client.py", line 120, in open
    self.list_spreadsheet_files()
  File "C:\Users\doug\p2venv\lib\site-packages\gspread\v4\client.py", line 94, in list_spreadsheet_files
    res = self.request('get', url, params=params).json()
  File "C:\Users\doug\p2venv\lib\site-packages\gspread\v4\client.py", line 79, in request
    raise APIError(response)
gspread.v4.exceptions.APIError: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }
}

I have no experience with accessing Google
Thanks
Doug

**Comment by burnash** [comment] 2018-04-06 09:55
This is a duplicate of https://github.com/burnash/gspread/issues/512 
Please also see the answer on StackOverflow:
https://stackoverflow.com/questions/49258566/gspread-authentication-throwing-insufficient-permission/49295205#49295205

**Closed by burnash** 2018-04-06 09:55 UTC
