### ISSUE TITLE
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581) when open sheet

### ISSUE THREAD

**Issue by airween** [burnash/gspread#276] opened 2015-07-09 14:34 UTC
Hi all,

I'm trying to use gspread on a new server, which's behind a HTTP proxy (Squid3). Here is the code:
```python
#!/usr/bin/python2.7
# -*- coding: utf8 -*-

import json
import gspread
import oauth2client.client
import os

os.environ['http_proxy'] = "http://127.0.0.1:3128"
os.environ['https_proxy'] = "http://127.0.0.1:3128"

json_key = json.load(open('gspr_service.json'))
scope = ['https://spreadsheets.google.com/feeds']

credentials = oauth2client.client.SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)

gc = gspread.authorize(credentials)
sh = gc.open("My sheet")
```

If I put a comment line to the start of the last line, the scipt returns successfully. If not, I got this stack:
```
  File "./sprtest1.py", line 18, in <module>
    sh = gc.open("My sheet")
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 134, in open
    feed = self.get_spreadsheets_feed()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 220, in get_spreadsheets_feed
    r = self.session.get(url)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 71, in request
    self.connections[uri.scheme+uri.netloc].request(method, url, data, headers=request_headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)
```
In access log of Squid3 there are these lines:
```
1436451793.701    249 127.0.0.1 TCP_MISS/200 5102 CONNECT 216.58.209.173:443 - HIER_DIRECT/216.58.209.173 -
1436451793.728      0 1.2.3.4 TAG_NONE/400 4023 NONE error:invalid-request - HIER_NONE/- text/html
```
(The 1.2.3.4 is my public IP).

There are several Python scripts, which using **gdata** libraries - but those are working as well, from same server (with same proxy settings). Anybody has any idea, what would be wrong?

Chears,

Ervin

**Comment by airween** [comment] 2015-07-09 15:54
So, it seems in trace stack, gspread uses httplib, which uses (Python) ssl - but looks like Python SSL library ignores the proxy enviroment values. The 2nd proxy log line shows that the request is intercepted, what means in that case the proxy works in transparent mode - but the transparent mode in SSL is not possible.
Now I opened the firewall to Google Spreadsheet server (216.58.209.174/32, port 443), and gspread works.

Does anybody an idea, how can I tell to the Python SSL library to use that proxy (not transparent mode?)

Thanks again,

Ervin

**Comment by msuozzo** [comment] 2015-10-15 01:50
Duplicate of #81.

**Closed by msuozzo** 2015-10-15 01:50 UTC

**Comment by jjhesk** [comment] 2020-10-10 18:24
any updates on this?

**Comment by amzar96** [comment] 2021-10-14 04:55
Any update on this? I faced the same issue.
