### ISSUE TITLE
I'm trying to print my dataframe and the error appears:

### ISSUE THREAD

**Issue by janderamancio** [burnash/gspread#1162] opened 2023-01-28 22:29 UTC
I'm trying to print my dataframe and the error appears:
sh = gc.open('name')

worksheet = sh.sheet1

df = pd.DataFrame(worksheet.get_all_records())
print(df)

File "C:\Users\Usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\gspread\worksheet.py", line 520, in get_all_records
    raise GSpreadException("the given 'expected_headers' are not uniques")
gspread.exceptions.GSpreadException: the given 'expected_headers' are not uniques

_Originally posted by @janderamancio in https://github.com/burnash/gspread/issues/986#issuecomment-1407501387_

**Comment by lavigne958** [comment] 2023-01-31 07:42
Hi please use the provided template when opening an issue.

This is a duplicate of #986

Closing this issue.

**Closed by lavigne958** 2023-01-31 07:42 UTC
