### ISSUE TITLE
Add typing on the arguments

### ISSUE THREAD

**Issue by shahriyardx** [burnash/gspread#1097] opened 2022-07-31 05:36 UTC
**Is your feature request related to a problem? Please describe.**
The function arguments are not typed. 

**Describe the solution you'd like**
Add typing on the arguments

**Describe alternatives you've considered**
N/A

**Additional context**
When I hover over the functions it shows Any as a type of every argument of the functions.
Yes they have docstrings but its better to have type on the arguments

### Current 
```py
def add_row(self, rows):
    pass
```

### Suggested
```py
def add_row(self, rows: int):
    pass
```

**Comment by lavigne958** [comment] 2022-07-31 11:11
Hi thank you for raising this issue, this is a duplicate of the issue #966 . which I am currently working on but takes a very long time to complete.

duplicate issue, closing this issue.

**Closed by lavigne958** 2022-07-31 11:11 UTC
