### ISSUE TITLE
gspread will not read Sheets once they are moved to a Team Drive folder

### ISSUE THREAD

**Issue by greed0179** [burnash/gspread#474] opened 2017-07-28 13:53 UTC
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System: Chrome OS
Python version: 2.7.6
gspread version: 0.4.1

### Stack trace or other output that would be helpful
When a Sheet is in a normal Google Drive directory, the sheet can be found without issue. Once that Sheet is moved into a Team Drive folder, gspread errors out with the 'SpreadsheetNotFound' message.

I am accessing the Sheet by id and that has not changed.

My service account is added with view access. 

I've checked the release history and see no mention of accessing Sheets in a Team Drive environment. Is this something that is being addressed?

**Comment by wgfm** [comment] 2017-08-11 12:52
I'm running into the same issue. I want to migrate some sheets to a team drive, but I'm running into `SpreadsheetNotFound` exceptions.

I did not forget to share the sheets with the appropriate service account.

**Comment by fhalamos** [comment] 2017-10-12 12:10
same here.. please help!

**Comment by iamshwin** [comment] 2017-11-21 15:21
I am also receiving SpreadsheetNotFound exception. Did anyone find any workarounds?

**Comment by appierys** [comment] 2017-12-01 01:43
same here 😩

**Comment by ryantuck** [comment] 2018-03-23 17:20
`pygsheets` appears to support this behavior. it also looks like it's got a ton of the same functionality as gspread does. might be worth taking a look: https://github.com/nithinmurali/pygsheets

**Comment by ryantuck** [comment] 2018-04-02 20:25
It appears that `gspread` works fine dealing with sheets in team drives, but only when attempting to open using the url or key of the spreadsheet:

```
In [127]: gs.open_by_url(url)
Out[127]: <Spreadsheet 'test team drive spreadsheet' id:xxxxxxxxxxxxxxxx>

In [128]: gs.open_by_key(spreadsheet_key)
Out[128]: <Spreadsheet 'test team drive spreadsheet' id:xxxxxxxxxxxxxxxx>

In [129]: gs.open('test team drive spreadsheet')
---------------------------------------------------------------------------
APIError                                  Traceback (most recent call last)
<ipython-input-129-73832fbe263c> in <module>()
----> 1 gs.open('test team drive spreadsheet')

/usr/local/lib/python3.6/site-packages/gspread/v4/client.py in open(self, title)
    101             properties = finditem(
    102                 lambda x: x['name'] == title,
--> 103                 self.list_spreadsheet_files()
    104             )
    105

/usr/local/lib/python3.6/site-packages/gspread/v4/client.py in list_spreadsheet_files(self)
     78             "?q=mimeType%3D'application%2Fvnd.google-apps.spreadsheet'"
     79         )
---> 80         r = self.request('get', url)
     81         return r.json()['files']
     82

/usr/local/lib/python3.6/site-packages/gspread/v4/client.py in request(self, method, endpoint, params, data, json, files)
     71             return response
     72         else:
---> 73             raise APIError(response)
     74
     75     def list_spreadsheet_files(self):

APIError: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }
}
```

**Comment by ryantuck** [comment] 2018-04-02 21:00
I've opened up a PR that fixes this: https://github.com/burnash/gspread/pull/527

**Comment by burnash** [comment] 2018-04-12 14:07
@greed0179 I'm closing this issue for now since I'm unable to reproduce it. Feel free to reopen it if you have an update.

**Closed by burnash** 2018-04-12 14:07 UTC
Labels: TTL
