### ISSUE TITLE
sort returns gspread.exceptions.APIError

### ISSUE THREAD

**Issue by kielni** [burnash/gspread#816] opened 2020-09-30 00:33 UTC
Calling sort as described in the docs

    spreadsheet.sheet1.sort((0, "asc"), (2, "des"), range="A2:I10000")

returns an exception instead of sorting the sheet:

    gspread.exceptions.APIError: {'code': 500, 'message': 'Internal error encountered.', 'status': 'INTERNAL'}

It looks like gspread is using the API described here: https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#sortrangerequest

But Google describes a different API here (also says API v4): https://developers.google.com/sheets/api/samples/data#sort_a_range_with_multiple_sorting_specifications

This sorts the sheet without an error:

    sort_req = {
        "sortRange": {
            "range": {"sheetId": 0, "startRowIndex": 0, "endRowIndex": 10000, "startColumnIndex": 0, "endColumnIndex": 9},
            "sortSpecs": [{"sortOrder": "ASCENDING", "dimensionIndex": 0}, {"sortOrder": "ASCENDING", "dimensionIndex": 2}],
        }
    }
    spreadsheet.batch_update({"requests": [sort_req]})

- Python version 3.6.4
- gspread version 3.6.0

Stack trace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kimberly/.pyenv/versions/webapps36/lib/python3.6/site-packages/gspread/models.py", line 1345, in sort
    response = self.spreadsheet.batch_update(body)
  File "/Users/kimberly/.pyenv/versions/webapps36/lib/python3.6/site-packages/gspread/models.py", line 146, in batch_update
    'post', SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/Users/kimberly/.pyenv/versions/webapps36/lib/python3.6/site-packages/gspread/client.py", line 73, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 500, 'message': 'Internal error encountered.', 'status': 'INTERNAL'}
```

**Comment by VerusK** [comment] 2021-03-15 09:19
don't know why but w/o `range` arg sorting works

**Comment by lavigne958** [comment] 2022-02-15 22:47
Hi @kielni 

I took a look on your issue, and the problem is not the `range`. The problem is that you use a 0-based index for your column index. or in gspread we use a 1-based index.

try your code but using a 1-based index, with first column A is 1 and column B is 2 etc and it works (with latest version of gspread :slightly_smiling_face: )

closing this issue.

**Closed by lavigne958** 2022-02-15 22:47 UTC
Labels: Bug, Need investigation
