### ISSUE TITLE
After installing Tornado v4.3, SSL_CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by Ralithune** [burnash/gspread#354] opened 2016-02-15 18:50 UTC
Hello everyone.

I'm running a collection of Python scripts on my box, and one of them requires the pip package [Tornado](url http://www.tornadoweb.org/en/stable/).

After installing it with pip, Gspread now refuses to work and throws an error:

`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)`

Here is the relevant portion of the stack trace:

```
 File "/usr/lib/python2.7/site-packages/gspread/client.py", line 145, in open
    feed = self.get_spreadsheets_feed()
  File "/usr/lib/python2.7/site-packages/gspread/client.py", line 231, in get_spreadsheets_feed
    r = self.session.get(url)
  File "/usr/lib/python2.7/site-packages/gspread/httpsession.py", line 75, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/gspread/httpsession.py", line 67, in request
    response = func(url, data=data, headers=request_headers)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
```

**Comment by kaidokert** [comment] 2016-02-15 20:31
This is totally unrelated to gspread, its a certificate verification issue on older python versions. I worked around this by downgrading/pinning 'certifi' package which is an indirect dependency. 
Try pip uninstall certifi && pip install certifi==2015.4.28, 2015.9.6, 2015.9.6.2 .. one of those should work again

**Comment by Ralithune** [comment] 2016-02-15 20:45
Good god, you just saved me days of time.  I'm running things on CentOS 7.1, so the Python version is 2.7.5.

```
pip install certifi==2015.4.28
pip install tornado
```

Works great, and solved this issue for me.

**Comment by jereze** [comment] 2016-02-23 11:12
Thank you, I also had the problem. Seems related to Python version.

**Comment by joeb-git** [comment] 2016-07-10 21:16
Thank you for this solution

**Comment by burnash** [comment] 2016-12-07 15:52
I'm closing this as the issue is not related to gspread.

**Closed by burnash** 2016-12-07 15:52 UTC
