### ISSUE TITLE
[5.4.0] While sorting, a frozen row is always sorted

### ISSUE THREAD

**Issue by MarcoBorrini99** [burnash/gspread#1089] opened 2022-07-16 12:47 UTC
While using 5.4.0 version, If I sort a table by first column with the first row frozen, that row is sorted anyway.

Reading docs I see: "range (str) – The range to sort in A1 notation. By default sorts the whole sheet excluding frozen rows". If I don't misunderstand, if I don't use 'range' the first frozen row in my sheet should not be sorted.

1. `wks_arcade.freeze(rows = 1)`
My worksheet has the first row correctly frozen

2. `wks_arcade.sort((1, 'asc'))`
The worksheet got sorted including first row (containging headers)

3. `print(wks_arcade.frozen_row_count)`
It outputs 0 (sadly I'd say...)

**Environment info:**
- Archlinux
- Python version: 3.10.4
- gspread version: 5.4.0

ps:
`wks_arcade.sort((1, 'asc'), range='A2:M2825')`
works as expected but I always have to calculare the lower right corner of my table

pss: I hope it's clear what I'm trying to achieve!

**Comment by lavigne958** [comment] 2022-07-16 17:31
Hi thank you for raising this issue.

This is a confirmed bug. I found out why it does not work.

first of all the method `sort` should be reworked, the signature uses some old school style python signature for no reasons (any more).

Then you should know that when you read some sheet properties (like `frozen_row_count`) they can be outdated, the sheet properties are fetched when fetching the worksheet. Then if you update some properties the local instance of `Worksheet` is not updated accordingly (this is a known issue that I don't know how to tackle :slightly_frowning_face: )

Then I noticed the method `sort` is lever enough to read the sheet properties and skip the frozen rows **if you don't** provide a range.

In your case you can use the following workaround that will work:

1. freeze your first row
2. fetch the worksheet again (using one of the methods: `get_worksheet()` or `worksheets()` or `worksheet()` or `get_worksheet_by_id()`)
3. then you can use `sort((1, 'asc'))` which will sort your sheet and skip the frozen rows. because you fetched the worksheet again after freezing the row it gets the sheet properties with the latest update. so it works :heavy_check_mark:  :slightly_smiling_face:

I still need to find a way to simplify this but in the end the solution is updating the sheet properties when changing them, which is a bi change.

**Comment by MarcoBorrini99** [comment] 2022-07-16 19:49
> Hi thank you for raising this issue.
> 
> This is a confirmed bug. I found out why it does not work.
> 
> first of all the method `sort` should be reworked, the signature uses some old school style python signature for no reasons (any more).
> 
> Then you should know that when you read some sheet properties (like `frozen_row_count`) they can be outdated, the sheet properties are fetched when fetching the worksheet. Then if you update some properties the local instance of `Worksheet` is not updated accordingly (this is a known issue that I don't know how to tackle slightly_frowning_face )
> 
> Then I noticed the method `sort` is lever enough to read the sheet properties and skip the frozen rows **if you don't** provide a range.
> 
> In your case you can use the following workaround that will work:
> 
> 1. freeze your first row
> 2. fetch the worksheet again (using one of the methods: `get_worksheet()` or `worksheets()` or `worksheet()` or `get_worksheet_by_id()`)
> 3. then you can use `sort((1, 'asc'))` which will sort your sheet and skip the frozen rows. because you fetched the worksheet again after freezing the row it gets the sheet properties with the latest update. so it works heavy_check_mark  slightly_smiling_face
> 
> I still need to find a way to simplify this but in the end the solution is updating the sheet properties when changing them, which is a bi change.

Thanks for the reply!  To tell the true, I've applied a very horrible hack becouse I can't re-fetch the worksheet because it's created each time I run my script (it's built with the data of three different sheets).
```
range_first_row = str('2')
range_first_col = 'A'
range_last_row = str(wks_arcade.row_count)
range_last_col = chr(ord('@') + wks_arcade.col_count)
range_data = range_first_col + range_first_row + ':' + range_last_col + range_last_row
wks_arcade.sort((1, 'asc'), range=range_data)
```

**Comment by lavigne958** [comment] 2022-07-17 16:17
I don't understand what is preventing you from fetching the worksheet again :thinking: 

Here is a sample code that:
1. creates a new worksheet
2. freeze one row
3. get the same worksheet again (including up to date sheet properties)
4. sorts some columns

```python

import gspread

gc = gspread.service_account()
sphs = gc.open("TestGspread")

# create new worksheet
sh = sphs.add_worksheet("new sheet", 6, 4)
sh.update("A1:D1", values=[["ID", "Name", "Firstname", "Score"]])
sh.update(
    "A2:D6",
    values=[["0", "a", "b", "0"], ["1", "c", "d", "100"], ["2", "e", "f", "50"]],
)

# freeze row 1
sh.freeze(1)

# get sheet again
copy_sh = sphs.get_worksheet_by_id(sh.id)

# sort table
copy_sh.sort((4, "des"))
```

Let me know where your issue is located in the above code sample

**Comment by MarcoBorrini99** [comment] 2022-07-30 18:07
> I don't understand what is preventing you from fetching the worksheet again thinking
> 
> Here is a sample code that:
> 
> 1. creates a new worksheet
> 2. freeze one row
> 3. get the same worksheet again (including up to date sheet properties)
> 4. sorts some columns
> 
> ```python
> import gspread
> 
> gc = gspread.service_account()
> sphs = gc.open("TestGspread")
> 
> # create new worksheet
> sh = sphs.add_worksheet("new sheet", 6, 4)
> sh.update("A1:D1", values=[["ID", "Name", "Firstname", "Score"]])
> sh.update(
>     "A2:D6",
>     values=[["0", "a", "b", "0"], ["1", "c", "d", "100"], ["2", "e", "f", "50"]],
> )
> 
> # freeze row 1
> sh.freeze(1)
> 
> # get sheet again
> copy_sh = sphs.get_worksheet_by_id(sh.id)
> 
> # sort table
> copy_sh.sort((4, "des"))
> ```
> 
> Let me know where your issue is located in the above code sample

You're perfectly right, I didn't read carefully documentation and what you wrote.

**Comment by lavigne958** [comment] 2022-07-31 11:05
Perfect :+1: 

Closing this issue then.

**Closed by lavigne958** 2022-07-31 11:05 UTC
Labels: Bug
