### ISSUE TITLE
Error when trying to create a .exe using PyInstaller

### ISSUE THREAD

**Issue by Alaix27** [burnash/gspread#347] opened 2016-01-24 18:25 UTC
Hi,

I'm currently working on a project that heavily relies on gpsread. I'm in charge of creating a .exe but I've been running into some problems... I have PyOpenSSL installed and the program works fine from the .py

I'm doing some testing on a simple (and working!) program that does the following:
- Connects to a spreadsheet using gspread
- Get information from a specific cell from the spreadsheet
- Update information of a specific cell on the spreadsheet

When trying to make the .exe using PyInstaller, I get the following :

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "CurrentMouse.py", line 53, in spreadsheetOpen
  File "site-packages\oauth2client\util.py"m line 140 in positional_wrapper
  File "site-packages\oauth2client\client.py", line 1630, in **init**
  File "site-packages\oauth2client\client.py", line 1581, in _RequireCryptoOrDie

oauth2client.client.CryptoUnavailableError: No crypto library available
google22nov returned -1

**Comment by burnash** [comment] 2016-12-07 19:24
From the traceback, it looks like the issue is related to [oauth2client](https://github.com/google/oauth2client) which is a separate project. I'm closing this issue.

**Closed by burnash** 2016-12-07 19:24 UTC
