### ISSUE TITLE
row_values() now returns empty values

### ISSUE THREAD

**Issue by jereze** [burnash/gspread#352] opened 2016-02-04 14:07 UTC
Hi,

I noticed that with the last version of gspread, `gspread.Worksheet.row_values()`return a list containing empty values.

Here is how to reproduce:

Any spreadsheet:
![capture d ecran 2016-02-04 a 15 05 11](https://cloud.githubusercontent.com/assets/4386500/12817140/c173665c-cb50-11e5-858b-e276d9672289.png)

debug.py

```
import gspread
import json
from oauth2client.client import SignedJwtAssertionCredentials

json_key = json.load(open('/path/to/.../CredentialsGoogleDriveAPI.json'))
scope = ['https://spreadsheets.google.com/feeds']
credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
gc = gspread.authorize(credentials)

sheet = gc.open_by_key('1vpxjREK9nui9n3olhCDNghrNaKoEBVELIqHqlSY43tc').sheet1

print gspread.__version__
print sheet.row_values(1)
print sheet.row_values(2)
```

Running with Gspread 0.2.5:

```
$ python debug.py 
0.2.5
['Test']
[]
```

Running with Gspread 0.3.0:

```
$ python debug.py 
0.3.0
['Test', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
```

**Comment by jimt** [comment] 2016-03-03 07:58
The same is true of `gspread.Worksheet.col_values()`, and as your example shows, the "empty" cells are returning empty strings rather than documented `None`.

**Comment by burnash** [comment] 2020-03-30 15:04
Hi, sorry for the late response. 
I can't reproduce the issue and I think this has been addressed long time ago. 
Closing the issue for now. 
If you still experience this problem, I believe upgrading to the latest version of gspread should solve it. If not feel free to open a new issue.

**Closed by burnash** 2020-03-30 15:04 UTC
Labels: Bug
