### ISSUE TITLE
Gspread share function does not send email notifications anymore

### ISSUE THREAD

**Issue by rathegod1992** [burnash/gspread#697] opened 2019-10-07 09:23 UTC
Hi, i am using python 3.7.1 with **gspread** library version 3.1.0.

Until the 4th of October 2019, every time i shared a spreadsheet with a user, that user received an email notification. My share function is like this:

    def share_spreadsheet_with_users(self, users_to_share_with):
        """

        :param users_to_share_with: the users with whom the spreadsheet will be shared
        :return:
        """
        for user in users_to_share_with:
            **self.spreadsheet.**share(user, perm_type='user', role='writer')

In the code above, the **self.spreadsheet** is a newly created spreadsheet and has type: `gspread.Client`

Ever since 4th October the user is only shared the spreadsheet (which can be seen in the google drive) but the user is **NOT** also notified on email. What could be the issue ?

**Comment by coyotevz** [comment] 2019-10-11 04:01
Hello, we have the same problem from the same moment (October 4), any comment is welcome.
Using argument ``notify=True`` doesn't help either.
Regards.

**Comment by irenkamk** [comment] 2019-10-30 08:50
Hello, one more confirmation about this problem. We also don't receive any emails any more. 
I hope we can get some feedback soon (confirmation of the issue) and if possible solutions are in sight!
Many thanks!

**Comment by Irina1989** [comment] 2019-10-30 10:33
Hi, same here, there is no email sent anymore since beginning of October. Would be very thankful if that got fixed!

**Comment by irenkamk** [comment] 2019-10-31 18:15
update: the email notifications started working today again :-) I think the issue can be closed

**Comment by coyotevz** [comment] 2019-10-31 21:13
Confirmed, notifications is working again.

**Comment by burnash** [comment] 2019-11-01 09:18
@irenkamk @coyotevz thank you for the news :) Closing the issue.

**Closed by burnash** 2019-11-01 09:18 UTC

**Comment by rathegod1992** [comment] 2020-05-20 12:57
Hi @burnash  ,

It seems that this issue is back. The spreadsheet is shared but the notification is not sent.

Regards,
Sergiu

**Comment by burnash** [comment] 2020-05-20 14:01
@rathegod1992 Thanks for reporting. Previous time it looked like the problem was on Google Sheets API end (e.g. server-side, not related to gspread or other client libraries). I have a strong feeling it the same now.

**Comment by rathegod1992** [comment] 2020-05-20 15:00
Thanks for your response, @burnash  .

I will comment back here when the problem is gone and email notifications are sent again.

**Comment by yeahyeahyo** [comment] 2020-05-23 16:47
+1 
Same problem here, since last week.

**Comment by sinhprous** [comment] 2020-05-24 09:17
Same problem +1

**Comment by emiraydin** [comment] 2020-05-24 09:37
Same here +1, was working last week

**Comment by ItayGal2** [comment] 2020-05-31 20:49
Me too, still not working

**Comment by rathegod1992** [comment] 2020-06-03 08:44
Hi @burnash ,

It seems that the google service for mail notification is working again. Starting from 2 June 2020.

Thanks.

**Comment by rathegod1992** [comment] 2020-07-13 13:21
Hi @burnash ,

The same issue occurs since 11th of July 2020. The notification is not sent on mail. If this is a google service issue why does it reproduce ?

Regards,
Sergiu.

**Comment by rathegod1992** [comment] 2020-07-13 13:51
> @rathegod1992 thanks for reporting.
> 
> > If this is a google service issue why does it reproduce ?
> 
> Sorry, I don't understand what you mean. Could please you elaborate?

Hi @burnash , yes i can elaborate. So, last time when this issue reappeared you said that it was **Most likely an API backend issue.** .

My question is perhaps not a good one. I just want to understand why this issue occurs from time to time and cannot be solved once and for all.

Thank you,
Sergiu.

**Comment by burnash** [comment] 2020-07-13 15:46
@rathegod1992 Thank you for clarification. What version of gspread are you currently using? Did you install it from PyPI or GitHub?

**Comment by rathegod1992** [comment] 2020-07-13 16:18
@burnash ,

I have the same versions as in the description of this ticket: i am using python 3.7.1 and gspread library version 3.1.0.
Gspread is installed in my venv through command: pip install gspread==3.1.0
So i guess gspread is taken from git.

Thanks for your support,
Sergiu.

**Comment by burnash** [comment] 2020-07-13 18:15
Thank you for elaborating. Yes, I do think that this issue is very likely not related to gspread. Here's why:

1. gspread is simply an API wrapper and does not send email notifications by itself. Here's how it works. When you call `Spreadsheet.share` it [calls](https://github.com/burnash/gspread/blob/aa119dba20ebaed4d7c247a45700826a899991e8/gspread/models.py#L494-L502) `Client.insert_permission`. `insert_permission` is in turn also [a very simple API call](https://github.com/burnash/gspread/blob/aa119dba20ebaed4d7c247a45700826a899991e8/gspread/client.py#L367-L382) to Google Drive API [Permissions: insert](https://developers.google.com/drive/api/v2/reference/permissions/insert). Notification emails are controlled by `sendNotificationEmails` parameter which was `True` by default since this commit https://github.com/burnash/gspread/commit/c83f312c40809277cc5ba2cebe10afec7f6d42fd from 2016.
2. You're using pip which means, you've installed gspread 3.1.0 from PyPI. Here's how `client.py` looks like in this release: https://github.com/burnash/gspread/blob/1bf2ca65c67f8e4cb3626e91fc43cebfb29611aa/gspread/client.py. As you can see the notification setting (`sendNotificationEmails`) is `True` by default. 

If you haven't changed gspread version since posting this issue and the problem resolved and reappeared on its own I would say that there's a very high probability that it has nothing to do with gspread.

**Comment by rathegod1992** [comment] 2020-07-14 08:16
Thank you @burnash for the answer. The notifications started to work again today.

Regards,
Sergiu.

**Comment by Askani007** [comment] 2020-12-07 07:16
Same problem today +1

**Comment by Muskan-ai** [comment] 2020-12-07 13:26
I was able to notify others when i shared the spreadsheet until 3 dec 2020. Today I am unable to do it :(
Why is it happening now?

**Comment by Askani007** [comment] 2020-12-07 13:31
Yes Muskan-ai, me too facing with the same error

**Comment by justinaugust** [comment] 2021-03-26 22:34
I am unable to turn off notification emails now.
`
        permission = google_sh.InsertPermission({
                        'sendNotificationEmails' : 'False',
                        'type': 'user',
                        'value': 'MYEMAIL',
                        'role': 'writer'
                        })`
                        
                        Any insight?
