### ISSUE TITLE
Adding new rows doesn't increase row count property

### ISSUE THREAD

**Issue by cgmorton** [burnash/gspread#545] opened 2018-05-04 06:12 UTC
### Environment info

Operating System: MacOS Sierra
Python version: 3.6.3 (Miniconda)
gspread version: 3.0.0

### Steps to reproduce
ws = sheet.worksheet('Sheet1')
print(ws.row_count)
ws.add_rows(1)
print(ws.row_count)

**Comment by uneasyguy** [comment] 2018-05-08 11:53
I too am having this issue if anyone can lend a hand

**Comment by crash5936** [comment] 2018-05-16 09:01
The issue is actually larger than that - the `Worksheet` instance seems to never update its properties after changing them, the same goes for `self.col_count` and `self.title` properties.

I think the issue could be fixed by updating the `Worksheet` instance properties every time after calling `self.batch_update()`

**Comment by cgmorton** [comment] 2018-05-16 13:18
You're right!  Let me know if it would help if I modified the title of this issue to better describe the problem.  Or I could close this issue if you want to start a new one.

**Comment by crash5936** [comment] 2018-05-16 13:55
I tried fixing the issue and opened a pull request, it fixed all the issues for me, let's see if it's viable and we can get this merged into master :)

**Comment by python-engineer** [comment] 2020-05-10 11:25
> I tried fixing the issue and opened a pull request, it fixed all the issues for me, let's see if it's viable and we can get this merged into master :)

I would love to see this one merged

**Comment by tlhinman** [comment] 2021-01-11 22:01
Any updates on this? This is a pretty big impediment for us right now.

**Comment by Acendro** [comment] 2021-01-29 14:31
Can't you just bypass the issue with saving row_count into a variable before appending and then incrementing it everytime you append a row during the code afterwards?
Works fine for me at least

**Comment by lavigne958** [comment] 2021-05-24 09:42
Hi this is a bigger issue in fact, as none of the properties are up to date after changing them. 

I think the simplest way of solving this for now is to update local properties when an update is successful.
So for instance calling `add_rows` will increase the local `row_count` value. this can lead to mistakes still because someone could be updating the sheet from an other script or from a web browser. but still it solves the issue for single access.

**Comment by kuznetsov-m** [comment] 2022-04-05 13:26
I have the same problem like issue starter.

**Comment by alifeee** [comment] 2023-06-08 17:13
Fixed by #1211?

**Comment by lavigne958** [comment] 2023-06-14 13:12
yes closed by #1211

**Closed** 2023-06-14 13:14 UTC
Labels: Bug

**Comment by alifeee** [comment] 2023-06-14 14:42
this specific method is fixed, but there is still the same issue if you use other methods such as `append_rows` or `insert_rows`

see https://github.com/burnash/gspread/issues/881#issuecomment-1591337773
