### ISSUE TITLE
401 Unauhtorized after inserting 150 rows - am I being throttled ?

### ISSUE THREAD

**Issue by medyagh** [burnash/gspread#402] opened 2016-07-24 16:29 UTC
I tried three times and each time after inserting 150 rows, google sheets kicks me out and and gspread thinks I am not auhtorized.

```
line 288, in save_to_gsheet
    worksheet.update_cell(u.row, key_col, eval("self." + k))
  File "/usr/local/lib/python3.5/dist-packages/gspread/models.py", line 433, in update_cell
    self._cell_addr(row, col))
  File "/usr/local/lib/python3.5/dist-packages/gspread/client.py", line 203, in get_cells_cell_id_feed
    r = self.session.get(url)
  File "/usr/local/lib/python3.5/dist-packages/gspread/httpsession.py", line 76, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gspread/httpsession.py", line 72, in request
    response.status_code, response.content))
gspread.exceptions.HTTPError: 401: b'<HTML>\n<HEAD>\n<TITLE>Unauthorized</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Unauthorized</H1>\n<H2>Error 401</H2>\n</BODY>\n</HTML>\n'
```

I am thinking this is probably a throttling issue by google ? how can I catch the exact exception "gspread.exceptions.HTTPError' . and maybe make it wait a few minutes and relogin again .
I tried to catch HTTPError but I believe it it not imported. which module or package do I need to import ?

**Comment by medyagh** [comment] 2016-07-24 19:08
update I found the answer to one of my questions:
to catch ht HTTPError (you need to give the full name if you are only importing gspread) 
`except gspread.exceptions.HTTPError:`

I will try to make it re-authorize to see if it will help.

**Comment by gvandesompel** [comment] 2016-07-29 16:17
I am facing the same problem: Gspread error 401 after a while running my python program. I am stuck. Any help here please...?

**Comment by bryzgaloff** [comment] 2016-08-10 12:41
Today faced quite the same issue: after a night running gspread refused to modify the spreasheet. Unfortunately I have no logs, because it was running not in main thread but I guess the problem is that Google session expires. Have anyone tried to recreate a credentials instance? I'm going to try it out.

**Comment by burnash** [comment] 2018-07-29 14:59
Sorry for the late response.

gspread has been ported to a newer Sheets API v4. I believe upgrading to the latest version should solve this issue. I also noticed that v4 error messages are much clearer (especially in regard to limits and quotas.

I'm closing this issue, feel free to re-open it if you still experience the error.

**Closed by burnash** 2018-07-29 14:59 UTC
