### ISSUE TITLE
Cells with leading 0's - Gspread doesn't receive data as formatted on screen?

### ISSUE THREAD

**Issue by Ralithune** [burnash/gspread#231] opened 2015-05-11 23:05 UTC
Hello all, this is my first time posting an issue to Github.

I am using Gspread in my Python script to pull down firmware versions of hard drives.  For many Seagate drives, those firmware revisions begin with 3 leading 0's - as in "0003" or "0004".

Google Spreadsheets is aggressive about reformatting these and attempts to make them just straight numbers - "3" and "4".  I can avoid this by setting the column to "Plain Text" via the menu:

Highlight Column -> Format -> Number -> Plain Text

I then enter the new values "4" -> "0004" and wait for the changes to be saved.

These values are not coming to Gspread literally, however - when they arrive in the hash, they arrive without the leading 0's: "4".

It should be noted that I can change the value to something like "ai3oerjgeij" and have it show up properly in my script, just not a number with leading 0's.

Is there some way I can avoid this aggressive data changing?  Google is sure assuming a lot when they do this by default - messing with data is dangerous.

**Comment by burnash** [comment] 2015-06-17 19:43
Sorry for the late reply. Could you please send a snippet of your code? Particularly a place where you're retrieving those values. This can help.

Thanks for the feedback :)

**Comment by Ralithune** [comment] 2015-06-19 23:37
Hey Burnash.  I'm just using sheet.get_all_records and looping through that - the values in the dict are altered when they arrive.

I've taken to adding "googleisdumb" to my numbers to work around this, so "googleisdumb0004" and then manually parsing out the "googleisdumb" in my python script.  Hacky.

**Comment by msuozzo** [comment] 2015-10-12 02:41
This is desired behavior for spreadsheets so, unfortunately, I feel that it's out of scope to adjust this behavior in gspread. What data are you representing with leading zeros?

**Closed by msuozzo** 2015-10-12 02:41 UTC

**Comment by Ralithune** [comment] 2016-07-11 18:09
@msuozzo I'm representing drive firmware levels.  For Seagate SAS drives, their firmware rev appears as "0003" or "0004" when queried by Smartctl and proprietary SAS controller binaries.

The spreadsheet serves as documentation for these values, so when they appear as "4" and not "0004", that is not an exact match to the disk firmware level.

Furthermore, when my software is comparing these values, it tries to compare "0004" to "4" and finds them inequal.  There's absolutely no reason for me to convert them to int - I just need the literal string to be uploaded and displayed as I wrote it with no alteration.

I'd have thought that would be default behavior when it comes to any kind of spreadsheet software, but apparently I'm wrong.

Is there a way to accomplish this?  Is Gspread munging the values or is Google?

**Comment by mattrussell2** [comment] 2018-11-02 22:37
same issue still exists. 
it's a good point - it's one thing for leading zeros to be chopped off of integers, but doesn't make sense to chop them off of strings.

any fixes yet?

**Comment by burnash** [comment] 2018-11-06 12:39
@mattrussell2 could you describe the issue you're experiencing? I'm considering reopening the issue.

**Comment by burnash** [comment] 2018-11-06 12:41
Related: #581

**Comment by mattrussell2** [comment] 2018-11-12 23:54
Hi - the issue is that when sending any value to a sheet using acell, if there is a prepending zero it gets cut off (even if it's a string). This may be a google sheets issue, and in that case it's unworkable...
