### ISSUE TITLE
cast_to_a1_notation(method)   bugs?

### ISSUE THREAD

**Issue by MiceKosu** [burnash/gspread#1055] opened 2022-05-30 23:29 UTC
cast_to_a1_notation(method) I believe there are bugs here

rowcol_to_a1()  does not want to take a list as in *args[:2]  but individual values

**Comment by lavigne958** [comment] 2022-05-31 12:35
Hi could you please provide a sample python code that illustrate the issue ?
I don't understand where is located the actual bug.

**Comment by MiceKosu** [comment] 2022-06-01 02:51
Hi, thank you for replying.  Honestly I might be in error. I was just completely not able to make this work. The below is from the utils segment of the library.

after I send a function like this 

`cast_to_a1_notation(ws.update(ws.update_cell(1, 1, 2, 2, content)))`

I was getting error:    "update accepts 2 or 3 arguments not 6..."  
not sure even how this line is supposed to work: `range_end = rowcol_to_a1(args[-2:])` - seems like the last two arguments are supposed to be the end of the range? There is little documentation on this.

When I looked at the function rowcol_to_a1 it would not want to work with argument of list of type [1,2] and preferred individual values 1,2.   So I am not sure how this is supposed to work. and it did not for me. I did convince myself that something must be wrong with this decorator function... so submitted a bug.  hopefully not overstepping from ignorance. 

Thanks!


`
def cast_to_a1_notation(method):
    """Decorator function casts wrapped arguments to A1 notation in range
    method calls.
    """

    @wraps(method)
    def wrapper(self, *args, **kwargs):
        try:
            if len(args):
                int(args[0])

                # Convert to A1 notation
                range_start = rowcol_to_a1(args[:2])
                range_end = rowcol_to_a1(args[-2:])
                range_name = ":".join((range_start, range_end))

                args = (range_name,) + args[4:]
        except ValueError:
            pass

        return method(self, *args, **kwargs)

    return wrapper`

**Comment by lavigne958** [comment] 2022-06-02 18:29
I think there is a misconception about this function.

This function (`cast_to_a1_notation`) should not be used directly when you use gspread. It is a special function that python will use if you use cell coordinates and it will translate this value to an A1 notation automatically, you don't have to do anything.

With an example, it means both of the following code samples are right and will work, gspread will handle both cases for you:

1. using A1 notation directly
```python
values = ws.range("A1:B2")
```
2. using cell coordinates
```python
values = ws.range(1, 1, 2, 2)
```

but in you case you are using the method `update` which does not handle that situation, so either you use A1 notation directly or you build it using the function `rowcol_to_a1` to get the A1 notation.
Remember if you choose the second option (build you A1 notation using `rowcol_to_a1` you must do like `cast_to_a1_notation`:
1. get the starting range: `start = rowcol_to_a1(1, 1)`
2. get the ending range: `end = rowcol_to_a1(2, 2)`
3. concat both with a colon `:`: `range = f"{start}:{end}"`
4. then you can pass it to the `update` method: `res = ws.update(range, content)`

I am closing this issue because it is not a bug in gpread, feel to comment here if you need more details.

**Comment by reece-anchorlabs** [comment] 2022-11-14 20:43
I can't comment on the original poster's issue, but I am having a related issue that the [`cast_to_a1_notation`](https://github.com/burnash/gspread/blob/d3df6d8b1945b8f295e624f2eeb36a4d1a00fb31/gspread/utils.py#L485) wrapper is not working with the `define_named_range` function.  I instead get the error that `define_named_range` expects 3 positional arguments and not 6:
```
ws.define_named_range(1,1,2,2,"range_name")
```
gives the error:
```
TypeError: define_named_range() takes 3 positional arguments but 6 were given
```
And yet
```
ws.range(1,1,2,2)
```
works just fine, returning a list of cells.  

Further, running:
```
ws.define_named_range(ws, 1,1,2,2,"name")
```
appears to actually engage the `cast_to_a1_notation` wrapper, as it at least gives the error
```
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Worksheet'
```
which is [defined within the wrapper](https://github.com/burnash/gspread/blob/d3df6d8b1945b8f295e624f2eeb36a4d1a00fb31/gspread/utils.py#L494).

**Comment by lavigne958** [comment] 2022-11-14 20:47
Hi I'll reopen this issue while I take a look at it. 

I'll try to run the code you provided.

**Comment by reece-anchorlabs** [comment] 2022-11-14 21:11
Thanks!  I didn't want to open a second Issue when I saw this one here.

**Comment by reece-anchorlabs** [comment] 2022-11-15 01:09
If it helps, I was able to get it to work with
```
def better_wrapper(method):
    @wraps(method)
    def wrapper(self,*args, **kwargs):
        try:
            if len(args):
                int(args[0])
                range_start = gspread.utils.rowcol_to_a1(*args[0:2])
                range_end = gspread.utils.rowcol_to_a1(*args[2:4])
                range_name = ":".join((range_start,range_end))
                args = (range_name,)+args[4:]
        except ValueError:
            pass
        return method(self, *args, **kwargs)
    return wrapper

class MoreBetterWorksheet(gspread.worksheet.Worksheet):
    def __init__(self, spreadsheet, properties):
        super().__init__(spreadsheet, properties)
        
    @another_wrapper
    def range(self, name=""):
        range_label = gspread.utils.absolute_range_name(self.title, name)

        data = self.spreadsheet.values_get(range_label)
        
        if ":" not in name:
            name = data.get("range", "")
            if "!" in name:
                name = name.split("!")[1]

        grid_range = gspread.utils.a1_range_to_grid_range(name)

        values = data.get("values", [])

        row_offset = grid_range.get("startRowIndex", 0)
        column_offset = grid_range.get("startColumnIndex", 0)
        last_row = grid_range.get("endRowIndex", self.row_count)
        last_column = grid_range.get("endColumnIndex", self.col_count)

        if last_row is not None:
            last_row -= row_offset

        if last_column is not None:
            last_column -= column_offset

        rect_values = gspread.utils.fill_gaps(
            values,
            rows=last_row,
            cols=last_column,
        )

        return [
            gspread.cell.Cell(row=i + row_offset + 1, col=j + column_offset + 1, value=value)
            for i, row in enumerate(rect_values)
            for j, value in enumerate(row)
        ]
    
    @another_wrapper
    def define_named_range(self, name, range_name):
        body = {
            "requests": [
                {
                    "addNamedRange": {
                        "namedRange": {
                            "name": range_name,
                            "range": gspread.utils.a1_range_to_grid_range(name, self.id),
                        }
                    }
                }
            ]
        }
        return self.spreadsheet.batch_update(body)
```
and then
```
ws = MoreBetterWorksheet(sh, my_properties)
ws.range(1,1,2,2)
ws.define_named_range(1,1,2,2,"my_range")
```
both work without issues.  This suggests that `cast_to_a1_notation` should be changed, with
```
range_start = rowcol_to_a1(*args[0:2])
range_end = rowcol_to_a1(*args[2:4])
```
Not sure if that would break any other methods, but it's more robust than the code there currently.

**Comment by lavigne958** [comment] 2022-11-15 07:43
Ho yes I see, yes that looks like the potential issue here. I will try that and if it's juste a matter of list indexes then we can quickly fix it

**Closed** 2024-03-02 10:48 UTC
Labels: Bug, in progress
