### ISSUE TITLE
append_row INVALID_ARGUMENT when appending more than one item at a time

### ISSUE THREAD

**Issue by mjeng** [burnash/gspread#551] opened 2018-05-21 05:14 UTC
Hi! I found an error when you append_row to a worksheet with a list with length > 1, IF the worksheet has a name with a colon `:` in it - other characters could cause this too, haven't tested comprehensively. I think this might be because gspread only expects one colon - as part of the error message, I got `Requested writing within range [':'!A3], but tried writing to column [B]`, even though I requested writing to a range larger than the one denoted. Or it might be because in order to denote a range, sheet name and colons are used in conjunction (e.g. `somesheet!A1:C1`), but when a colon is used, special formatting must be used (e.g. `'0:00'!A1:C1`), and this messes with gspread's parsing. Or something else.

### Environment info

Operating System: macOS 10.13.2
Python version: 3.6.5
gspread version: 3.0.0

### Steps to reproduce
1. Create a worksheet with a name containing the colon character `:`
2. Get your pointer to the worksheet, e.g. `ws`
3. Run `ws.append_row(['some', 'values'])`

### Stack trace or other output that would be helpful
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/owner/anaconda/lib/python3.6/site-packages/gspread/models.py", line 702, in append_row
    return self.spreadsheet.values_append(self.title, params, body)
  File "/Users/owner/anaconda/lib/python3.6/site-packages/gspread/models.py", line 100, in values_append
    r = self.client.request('post', url, params=params, json=body)
  File "/Users/owner/anaconda/lib/python3.6/site-packages/gspread/client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
  "error": {
    "code": 400,
    "message": "Requested writing within range [':'!A3], but tried writing to column [B]",
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by Ostapp** [comment] 2019-03-20 10:53
Having the same issue

**Comment by patcon** [comment] 2019-04-15 19:12
Hitting same thing. Haven't got it sorted, but I believe this has to do with `append_row()`:

https://github.com/burnash/gspread/blob/0e8debe208095aeed3e3e7136c2fa5cd74090946/gspread/models.py#L872-L891

which uses the `values_append()` under the covered:

https://github.com/burnash/gspread/blob/0e8debe208095aeed3e3e7136c2fa5cd74090946/gspread/models.py#L105-L120

Seems perhaps that append_row uses an old format for talking to the API, and the API reference docs look different (eg. no "values" param involved).

The clearer solution (without getting a PR into the library) likely involves using `values_append()` directly. Not sure what that involves yet

**Comment by patcon** [comment] 2019-04-15 19:49
Ahhhh seems that it's an issue with having colons in the sheet name, and it's an issue on the Google end, seemingly:
https://stackoverflow.com/questions/48212583/google-sheets-java-api-failing-to-append-values-to-multiple-columns

i removed the `:` from my worksheet name and it fixed everything. There might be a workaround that the library can do.

**Comment by patcon** [comment] 2019-04-15 20:18
Seems that both append and insert are broken at the API level. I didn't want my script to break unexpectedly just because someone renamed a worksheet, and so I found an alternative approach that allows me to use update actions, after sensing where the final row is on the sheet.

I used `ws.get_all_values()` to get a list of lists representing the whole table, then I kept track of how many rows I started with. So if that original `len()` was 30, I had 30 rows when I started. I then jumped to the next "free" row n+1, and updated it when I needed to append. I also needed to keep track of how many "inserts/updates", so that I knew where I should be updating for each desired append. Specially, I used the library's `ws.spreadsheet.values_update()` to make these updates.

Hopefully that helps others navigate! :) We could get a workaround into this library itself, but I'm not sure the author has time to accept PRs right now

**Comment by patcon** [comment] 2019-04-15 20:30
```
insert_count = 0
wsheet = get_worksheet_obj_somehow()
all_values = wsheet.get_all_values()
row_count = len(all_values)
for o in objs:
    match = find_match(o.id)
    if match:
        # do update
    else:
        # do "append" 
        range = "'{}'!{row}:{row}".format(wsheet.title, row=row_count+1+insert_count)
        params = {'valueInputOption': 'RAW'}
        body = {'values': [row_values]}
        # NOTE: append and insert endpoints in the Google Sheets API seem to have a bug, so using a hack a update for now.
        # See: https://github.com/burnash/gspread/issues/551_
        # TODO: Accomodate when no extra rows in table.
        wsheet.spreadsheet.values_update(range, params, body)
        insert_count += 1
```

**Comment by lavigne958** [comment] 2021-05-19 22:21
This has been fixed. Tried to append a row to a sheet containing a semicolon `:` in its name and it works.

Closing this issue.

**Closed by lavigne958** 2021-05-19 22:21 UTC

**Comment by liam-clifford** [comment] 2022-06-07 19:06
@lavigne958 This looks to still be a problem for values_update FYI

**Comment by lavigne958** [comment] 2022-06-08 12:04
Hi, yes it is, but this is not a bug, because the method `spreadsheet.values_update` is not intended to be used directly by a user. the `spreadsheet` and `worksheet` object have dedicated methods for all operations. All methods will use the function `utils.absolute_range_name` that will prevent this issue. 

If someone needs/wants to use directly the method, then they must cover the range name themselves (like other method do, using `utils.absolute_range_name` function).
