### ISSUE TITLE
Max retries exceeded. Failed to establish a new connection.

### ISSUE THREAD

**Issue by GreenGhost994** [burnash/gspread#819] opened 2020-10-05 20:46 UTC
Hello,
I have problem with 
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Max retries exceeded with url: /v4/spreadsheets/...?includeGridData=false (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000025782533B48>: Failed to establish a new connection: [WinError 10060] Próba połączenia nie powiodła się, ponieważ połączona strona nie odpowiedziała poprawnie po ustalonym okresie czasu lub utworzone połączenie nie powiodło się, ponieważ połączony host nie odpowiedział'))`

The problem arose when I used the same google account for 3rd project. I created 3 diffrent Cloud Platform projects with 3 diffrent spreedsheets. 
The problem is in the middle of the day when several people use script at the same moment (one project affects the other and nothing works.). 
I didn't find a solution. I'm trying to establish a new connection when I have this error, but it takes too long.

Does anyone know what can I do to avoid this problem?

**Comment by bastienboutonnet** [comment] 2020-11-14 11:39
@GreenGhost994 I have ran into this issue a few times in the past, my solution has been to simply apply some retrying to the part of my scripts that interact with the sheet. 

I am not sure if it is needed just on the connection acquisition or on all other operations (it's a bit painful to reproduce those rate limitations)

But let's imagine you have something like:

```python
import gspread
import pandas as pd

def get_values_from_worksheet():
    gc = gspread.service_account()
    workbook = gc.open('some workbook')
    worksheet = workbook.get_worksheet(0)
    df = pd.DataFrame(worksheet.get_all_values())
```

You could use something like the `@retry` decorators from [`retrying`](https://pypi.org/project/retrying/) or whatever framework

and do the following 

```python
import gspread
import pandas as pd
import retying

@retry(stop_max_attempt_number=3, wait_fixed=2000)
def get_values_from_worksheet():
    gc = gspread.service_account()
    workbook = gc.open('some workbook')
    worksheet = workbook.get_worksheet(0)
    df = pd.DataFrame(worksheet.get_all_values())
```

This would retry up to 3 times and wait 2 seconds between each retries. The `retrying` package (linked above) has a lot of other cool stuff.


However, a better solution would be to know if this rate limitation happens only when acquiring the connection or applies to all operations (as I said I was lazy and didn't care so much to find out --my hunch is that it probably applies to all operations).

I don't know if it makes sense to have `gspead` control such retries or whether it should be up to the user to employ proper retry logic but I'm sure @burnash will have an opinion on this.

**Comment by bignellrp** [comment] 2021-08-30 21:11
Is my error related or just similar. Not sure what’s causing it yet.

`2021-08-30 20:12:44,302] ERROR in app: Exception on /result [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2624)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Max retries exceeded with url: /v4/spreadsheets/1tyy_8sKM-N-JA6j1pASCO6_HRxvlhTuA3R0KysbVG9U/values/%27Dev%20Results%27 (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2624)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./routes/result.py", line 44, in result
    result = results()
  File "./services/get_spread.py", line 128, in __init__
    results_table = wsr.get_all_values()
  File "/usr/local/lib/python3.8/site-packages/gspread/utils.py", line 593, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/gspread/models.py", line 884, in get_all_values
    return self.get_values(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/gspread/utils.py", line 593, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/gspread/models.py", line 857, in get_values
    return fill_gaps(self.get(range_name, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/gspread/utils.py", line 593, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/gspread/models.py", line 1136, in get
    response = self.spreadsheet.values_get(range_name, params=params)
  File "/usr/local/lib/python3.8/site-packages/gspread/models.py", line 221, in values_get
    r = self.client.request('get', url, params=params)
  File "/usr/local/lib/python3.8/site-packages/gspread/client.py", line 64, in request
    response = getattr(self.session, method)(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/google/auth/transport/requests.py", line 480, in request
    response = super(AuthorizedSession, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Max retries exceeded with url: /v4/spreadsheets/1tyy_8sKM-N-JA6j1pASCO6_HRxvlhTuA3R0KysbVG9U/values/%27Dev%20Results%27 (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2624)')))
[pid: 25|app: 0|req: 1/3] 192.168.0.229 () {60 vars in 1325 bytes} [Mon Aug 30 20:12:44 2021] POST /result => generated 290 bytes in 39 msecs (HTTP/1.1 500) 3 headers in 179 bytes (1 switches on core 1)
192.168.0.229 - - [30/Aug/2021:20:12:44 +0100] "POST /result HTTP/1.1" 500 290 "http://footyappdev.richardbignell.co.uk/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "192.168.0.1"
2021-08-30 20:14:46,694 WARN received SIGTERM indicating exit request
2021-08-30 20:14:46,694 INFO waiting for nginx, uwsgi to die
Mon Aug 30 20:14:46 2021 - graceful shutdown triggered...
Gracefully killing worker 1 (pid: 25)...
Gracefully killing worker 2 (pid: 35)...
2021-08-30 20:14:49,697 INFO waiting for nginx, uwsgi to die
2021-08-30 20:14:52,700 INFO waiting for nginx, uwsgi to die
2021-08-30 20:14:55,703 INFO waiting for nginx, uwsgi to die
2021-08-30 20:14:56,705 WARN killing 'uwsgi' (11) with SIGKILL
2021-08-30 20:14:56,712 INFO stopped: uwsgi (terminated by SIGKILL)
root@Tower:~# 
`

**Comment by lavigne958** [comment] 2021-08-31 15:41
hi @bignellrp 

your issue seems to be with SSL that cannot decode the SSL packet.
after searching online I found that could be due to network packets that are mixed and not ordered or the server trying to talk using TLS1.0 and brakes when you do.

Unfortunately this issue is not located and gspread.
The `Max retries exceeded` is a side effects, your connection fails, you retry and it fails again and you reach the max retry value.

**Comment by bignellrp** [comment] 2021-08-31 15:46
Ah that could explain why it only fails on my docker instance.  I'll do some research on TLS1.0 and SSL. Thanks for the reply.

**Comment by bignellrp** [comment] 2021-09-03 07:30
I'd like to add that ive switched to tiangologs meinheld docker and im no longer getting this error.  docker run -t -i -e WEB_CONCURRENCY="1" -p 80:80 tiangolo/meinheld-gunicorn-flask

**Comment by lavigne958** [comment] 2022-02-09 20:28
This is not an issue with gspread, closing this issue.

**Closed by lavigne958** 2022-02-09 20:28 UTC
