### ISSUE TITLE
oauth2client.client.HttpAccessTokenRefreshError: internal_failure 

### ISSUE THREAD

**Issue by rwalton00** [burnash/gspread#418] opened 2016-11-21 00:31 UTC
### Environment info

Operating System: Windows 10
Python version: 2.7
gspread version: 0.3.0

### Steps to reproduce
I have the following auth code in a script that has been working well for over 6 months.

```
scope = ['http://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name("assets/My Project-....json",
                                                              scope)
google_client = gspread.authorize(credentials)
```

Now the script consistently fails with the following stack trace:

```
Traceback (most recent call last):
  File ".\my_gspread_script.py", line 24, in <module>
    google_client = gspread.authorize(credentials)
  File "c:...\appdata\local\enthought\canopy\user\lib\site-packages\gspread\client.py", line 331, in authorize
    client.login()
  File "c:...\appdata\local\enthought\canopy\user\lib\site-packages\gspread\client.py", line 101, in login
    self.auth.refresh(http)
  File "c:...\appdata\local\enthought\canopy\user\lib\site-packages\oauth2client\client.py", line 541, in refresh
    self._refresh(http)
  File "c:...\appdata\local\enthought\canopy\user\lib\site-packages\oauth2client\client.py", line 744, in _refresh
    self._do_refresh_request(http)
  File "c:...\appdata\local\enthought\canopy\user\lib\site-packages\oauth2client\client.py", line 812, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: internal_failure

```

I have checked my developer account and ensured the drive & sheets apis are enabled. I have also tried creating new service accounts. I have even tried connecting with an entirely different google account (I'm also making sure to share the spreadsheet with the email in the json file each time) and it does not seem to make any difference to the result.

**Comment by burnash** [comment] 2016-11-21 10:17
Is it a duplicate of http://stackoverflow.com/questions/40703452/how-to-solve-gspread-oauth-refresher-token-error ?

**Comment by burnash** [comment] 2016-11-21 17:02
Closed as SO duplicate.

**Closed by burnash** 2016-11-21 17:02 UTC

**Comment by rwalton00** [comment] 2016-11-21 18:20
Yes, I posted on SO too. Thanks for taking a look.
