### ISSUE TITLE
scope defining only by /feeds executing all functions

### ISSUE THREAD

**Issue by fredericomattos** [burnash/gspread#1078] opened 2022-07-08 16:32 UTC
I apologize for asking this question here, but StackOverflow votes down and closes questions that are not code problems, but general questions, so I had to open this issue on GitHub!

I use the scope this way and I can do everything in the worksheets, I never received any errors whether any method called:
```
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import datetime

scope = ['https://spreadsheets.google.com/feeds']
dicter = 'client_secret.json'
creds = ServiceAccountCredentials.from_json_keyfile_name(dicter, scope)
client = gspread.authorize(creds)

today = datetime.date.today()
spreadsheet = client.open_by_key('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
worksheet = spreadsheet.add_worksheet(title=str(today), rows=1000, cols=26)
worksheet.update('A1',[['test','test_2']])
```
If only with this scope I can already do everything in the worksheets, for what some peoples who use scopes like this for example:
```
scope = ["https://spreadsheets.google.com/feeds", 'https://www.googleapis.com/auth/spreadsheets]
```
Is there any real difference in usage?

**Comment by lavigne958** [comment] 2022-07-10 13:39
Hi @fredericomattos 

thank you for raising this issue, I never had such deep look before.

for the historical record I took the maintenance of gspread and the scopes where already setup and working fine.

I look on the google documentation web site and found that the scope `https://spreadsheets.google.com/feeds` was used when using the sheet API V3. Now we use the sheet API V4 which uses the scope: `https://www.googleapis.com/auth/spreadsheets`

When what I read [here](https://developers.google.com/sheets/api/guides/migration#authorize_requests) both are equivalent to reach some spreadsheet files and their properties and values.

The issue is when you try to open a spreadsheet file by name (we use the drive API V3 in that case) so you don't have the right scope to open the file by name. This is why gspread uses the following scopes:

- `https://www.googleapis.com/auth/spreadsheets`
- `https://www.googleapis.com/auth/drive`

Changing the scope will have for effect to change what your script can access (in term of ressources, like get some drive file or some spreadsheet properties etc). 

gspread sets for you the right scopes it is recommended to use them, and if you wish to prevent modifications of the spreadsheet you can use some _read-only_ scopes which will prevent you from making any updates and is a nice safe guard in some cases.

As there is no issue/featured required here I am closing this issue, but feel to comment if needed. :slightly_smiling_face:

**Closed by lavigne958** 2022-07-10 13:39 UTC
