### ISSUE TITLE
worksheet.insert_cols and then worksheet.add_cols does not work

### ISSUE THREAD

**Issue by thuguerre** [burnash/gspread#935] opened 2021-10-04 08:20 UTC
https://github.com/burnash/gspread/blob/90a728fac1c8f6fb38f19da588de0337697854cc/gspread/worksheet.py#L1151

if we use `worksheet.insert_cols` to insert X new columns at the middle of the worksheet (it works), and then call `worksheet.add_cols(X)`, it will not add 2 new columns at the end of the sheet. 

However, if I use instead `worksheet.add_cols(X x 2)`, it will work.

I guess `worksheet.insert_cols` does not update `self.col_count` used by `worksheet.add_cols`.

I will be happy to precise the bug if not clear enough.

**Comment by lavigne958** [comment] 2021-10-04 09:16
Hi @thuguerre thank you for raising this issue, I agree with you the value of the property `col_count` is not updated and so it makes the call to `add_cols` misbehaving.

This could be solved if you try to get the worksheet again using one of the functions like `spreadsheet.get_worksheet(0)`.
This will force gspread to fetch the latests metadata from the online spreadsheet.

This is a bigger issue we are facing in gspread for some time and still don't know how to solve it simply.

It is tracked by #881  and we face the same issue for rows already (tracked by #545 )

In a few words the issue is:
- we update sheet property online
- we need to have the same update locally
- doing the update will increase call API => this can lead to being **blocked** by google for `TooManyAPICalls` 

we need to find a way to update local properties and not increase the number of API calls.

**Comment by thuguerre** [comment] 2021-10-04 10:10
thanks for the workaround ! it works for me, and is safer than my x2 :)
I presume update API call does not return new metadata to update local ones ?

**Comment by lavigne958** [comment] 2021-10-04 11:16
I am sorry but what method do you refer to by "update API call" ?

the only way to update local properties of a spreadsheet is by getting the worksheet again, we don't have (yet) any method to update the local properties of a worksheet. The `SpreadSheet` class has a method to fetch the latest properties (`fetch_sheet_metadata`) but you still need to read the result and update your sheet properties etc manually.

**Comment by thuguerre** [comment] 2021-10-04 12:44
I was just asking for your original issue, in order to try to help. But I guess you have already verified that `self.spreadsheet.batch_update(body)` for instance (worksheet, line 1178) does not return metadata that can be used to update local ones.

For my own issue, the workaround is enough to go forward.

**Comment by lavigne958** [comment] 2021-10-04 13:09
Oh alright I get it.
Actually I need to double check, I think this method (`batch_update`) does not return the new properties, but I still need to double check.

I will close your issue then, we know the root cause of your actual issue so this one has a workaround and the root cause will be fixed at some point.

feel free to comment if you face any more issues related to this.

**Closed by lavigne958** 2021-10-04 13:09 UTC
Labels: Bug
