### ISSUE TITLE
update a cell with 50,000 chars - ERROR

### ISSUE THREAD

**Issue by omersi** [burnash/gspread#187] opened 2014-12-01 15:51 UTC
when trying to update a cell with string longer that 50,000 chars it kills the connection to the spreadsheet.
please issue a suitable warning

**Comment by burnash** [comment] 2015-04-17 16:05
I've updated gspread so now it returns a message along with this exception. Can you update the library, rerun your code and post the exception message? That'll be very useful for anyone who is trying to work with this amount of text.

**Comment by omersi** [comment] 2015-04-19 10:47
HI

I updated to 0.2.4

>>> len(a)
50487
>>> spreadsheet.sheet1.update_acell('a1',str(a))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/gspread/models.py", line 429, in
update_acell
    return self.update_cell(*(self.get_int_addr(label)), val=val)
  File "/Library/Python/2.7/site-packages/gspread/models.py", line 445, in
update_cell
    self.client.put_feed(uri, ElementTree.tostring(feed))
  File "/Library/Python/2.7/site-packages/gspread/client.py", line 273, in
put_feed
    if ex.code == 403:
AttributeError: 'HTTPError' object has no attribute 'code'

It's better since the connection remains open.

is that the intended behavior?

Omer

**Comment by burnash** [comment] 2015-04-21 22:25
@omersi fixed missing attribute, could you update and try again?

**Comment by msuozzo** [comment] 2015-10-11 20:36
I believe this is a duplicate of #148.

**Closed by msuozzo** 2015-10-11 20:36 UTC
