### ISSUE TITLE
'Worksheet' object has no attribute 'get_values'

### ISSUE THREAD

**Issue by juaiasi** [burnash/gspread#1018] opened 2022-03-30 17:14 UTC
**Describe the bug**
Today I started to get this error in Google Colab... **'Worksheet' object has no attribute 'get_values'**
Yesterday I had a problem in the authorization to connect with gspread, but it was resolved. But now this error appeared despite the code being the same.

**To Reproduce**
Try to use this following code with google colab (with some personal worksheet):
```
!pip install --upgrade gspread
!apt-get update # to update ubuntu to correctly run apt install

import gspread
from google.colab import auth
from google.auth import default

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

url_sheet = "https://docs.google.com/spreadsheets/d/.../"
sheet = gc.open_by_url(url_sheet)
wsheet_values = sheet.worksheet('Sheet Name').get_values('A:G') #line with error
```
You can also try to import just the function:

`from gspread.worksheet.Worksheet import get_values`

And it returns to me this error: "cannot import name 'Dimension' from 'gspread.utils' (/usr/local/lib/python3.7/dist-packages/gspread/utils.py)"

**Expected behavior**
It was suposed to return the data in the specified range as lists within a list

**Comment by juaiasi** [comment] 2022-03-30 18:59
I just solved the problem replacing "get_values" with "get", but I still don't know why it stopped accepting "get_values".

**Comment by lavigne958** [comment] 2022-03-30 19:16
In fact this is odd. It looks like some import broke down in the latest release. I will look at it

**Comment by lavigne958** [comment] 2022-03-31 10:29
> I just solved the problem replacing "get_values" with "get", but I still don't know why it stopped accepting "get_values".

Be aware you did not solve your problem, you only worked around it. This workaround is very close but there is a difference between`get` and `get_values`

`get` will return the range you request.
`get_values` will return the range but it will keep the shape of the range and put empty values when the cells are empty. In `get` you don't receive the empty values.

Make sure this does not brake your script.

**Comment by lavigne958** [comment] 2022-04-05 09:01
I ran some tests.

About:
> You can also try to import just the function:
`from gspread.worksheet.Worksheet import get_values`

This is expected. `get_values` is a method and not a function, so `get_values` is tight to a object so you can't import it alone. you must use it from an object, like:
```
wks = spreadsheet.worksheet('sheet 2')
wks.get_values()
```

Abous:
> Worksheet' object has no attribute 'get_values

this is strange, I ran your code in google colab and it works fine,out of the box. I would recommend you to check the spreadsheet url you provide, the sheet name and the access rights to your spreadsheet.

as you found a workaround and I could not reproduce using your code sample, I am closing this issue.

Feel free to comment if the issue still persist.

**Closed by lavigne958** 2022-04-05 09:01 UTC
Labels: Bug, Need investigation

**Comment by tgmcnaughton** [comment] 2022-09-04 21:56
I'm getting same error get_values() whereas get() works. 

`from gspread.worksheet.Worksheet import get_values
`
produces: 
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-24-a4cb13ad46c6>](https://localhost:8080/#) in <module>
      1 import pandas as pd
      2 df = pd.DataFrame
----> 3 from gspread.worksheet.Worksheet import get_values
      4 
      5 ss = gc.open_by_key('1NSqHLBI7LC-5aRHY80EM3PudnO8GyBy7Tb4E0A3v0Lw')

ModuleNotFoundError: No module named 'gspread.worksheet'


Also for me sh.get() works fine AND appears to handle empty values accurately. 
thx.
