### ISSUE TITLE
Cannot use default service account in Compute Engine

### ISSUE THREAD

**Issue by nissankarkifm** [burnash/gspread#820] opened 2020-10-06 10:40 UTC
I'm trying to figure out how I can use the service account associated with a Compute Engine without the need of a JSON file.  I cant seem to be able to do that in gspread.

Google has an example here: https://cloud.google.com/docs/authentication/production

`   from google.cloud import storage

    # If you don't specify credentials when constructing the client, the
    # client library will look for credentials in the environment.
    storage_client = storage.Client()

    # Make an authenticated API request
    buckets = list(storage_client.list_buckets())
    print(buckets)`

For them it just works. No JSON necessary. Can this be replicated in any way in gspread?

**Comment by niczky12** [comment] 2020-12-04 22:45
I'm trying to do the same thing with no luck. I was trying to use `google.auth` like so:

```python
import google.auth
import gspread

DEFAULT_SCOPES =['https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/drive']
creds, _ = google.auth.default(scopes=DEFAULT_SCOPES)

gc = gspread.authorize(creds)

gc.create("hello world")
```

**Comment by gpkc** [comment] 2020-12-10 14:31
@niczky12 Maybe try the following:

- Check the type of creds: `type(creds)` it must return `google.oauth2.service_account.Credentials`
- Check the service account e-mail: `creds.service_account_email` it must be the service account email you expect
- Check if the spreadsheet is shared with that service account email (I assume that's fine since you mentioned it works with JSON)

If the two first steps fail, make sure your Compute Engine / Google Kubernetes Engine / App Engine / Cloud Run / Cloud Function have the **right service account set** in its configurations. If you don't do that you'll have the default service account which might not be the same you're trying to use.

If you want to test that on your local computer, try setting the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to the **path** of the service account. That's not exactly what happens inside the google engines but `google.auth.default` should treat the same.

Finally, you can also try using `from googleapiclient._auth import default_credentials` instead of `google.auth.default` since that one is a bit more generic as it includes `oauth2client`.

**Comment by niczky12** [comment] 2020-12-11 14:57
@gpkc Thanks for getting back to me.

I tried the above, but getting a different type:

```python
>>> creds, _ = google.auth.default(scopes=DEFAULT_SCOPES)
>>> type(creds)
<class 'google.auth.compute_engine.credentials.Credentials'>
>>> creds.service_account_email
'default'
```

Also tried with `googleapicleint` but getting the same thing:

```python
>>> from googleapiclient._auth import default_credentials
>>> creds2 = default_credentials()
>>> type(creds2)
<class 'google.auth.compute_engine.credentials.Credentials'>
>>> creds2.service_account_email
'default'
```

This is running in a pod on GKE. The cluster is using the default compute service account. When I use that json key and set `GOOGLE_APPLICATION_CREDENTIALS` then I get the right behaviour:

```
>>> creds, _ = google.auth.default(scopes=DEFAULT_SCOPES)
>>> type(creds)
<class 'google.oauth2.service_account.Credentials'>
>>> creds.service_account_email
'...-compute@developer.gserviceaccount.com'
```

But would like to achieve the same without exposing my SA key.
Any idea why this is happening?

**Comment by gpkc** [comment] 2020-12-11 21:52
@niczky12 

>  The cluster is using the default compute service account

That is probably the issue. Make sure your cluster is set up using the service account you're thing to use. If you leave the default service account, your pods will inherit it.

In any case you don't have to expose your SA key anywhere too. You can use kubernetes secrets or even GCP secrets manager (but for this one you'd have to give the cluster's service account access to the secret).

**Comment by niczky12** [comment] 2020-12-14 09:30
That same default service account with a json key and setting `GOOGLE_APPLICATION_CREDENTIALS` works fine from the same pod. So there's something else going on.

I know I can add the key as a secret to k8s, but wanted to give this a go and I thought if I can figure out then I could add the steps to docs so that others can start using the application default credentials. Maybe, I'll have a look at the google.cloud modules and see how they discover the keys, because those work as expected.

**Comment by nissankarkifm** [comment] 2021-01-08 10:17
The following worked for me. Issue can be closed.
```
import pandas as pd

import gspread

import google.auth

import google.auth
credentials, project_id = google.auth.default(
    scopes=['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive'])

type(credentials)
<google.oauth2.service_account.Credentials>
gs_client = gspread.authorize(credentials)

sheet = gs_client.open_by_key('XXXXXXXXXX')

worksheet = sheet.worksheet("master")

df = pd.DataFrame(worksheet.get_all_records())

df.shape
<(18, 8)>
```

**Comment by niczky12** [comment] 2021-01-08 11:19
> The following worked for me. Issue can be closed.

What compute environment are you using? And what do you get if you run `echo $GOOGLE_APPLICATION_CREDENTIALS` ? I would like to isolate the issue and figure out if this is only affecting kubernetes or not.

**Comment by nissankarkifm** [comment] 2021-01-08 11:49
@niczky12  Oops. I spoke too soon it seems. I've updated my comment. 
The code ran fine on my local machine so I assumed it'd work on a compute engine as well. I should've tested it. My bad. 

When running the same code in a Compute Engine Instance, I get the following error. 

`APIError: {'code': 403, 'message': 'Request had insufficient authentication scopes.', 'status': 'PERMISSION_DENIED'}`

**Comment by nissankarkifm** [comment] 2021-06-28 13:11
> @niczky12 
> Finally, you can also try using `from googleapiclient._auth import default_credentials` instead of `google.auth.default` since that one is a bit more generic as it includes `oauth2client`.

This worked for me on a cloud function, but not on compute engine. 

```
DEFAULT_SCOPES = ['https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/drive']
CREDENTIALS = default_credentials(scopes=DEFAULT_SCOPES)
client = gspread.authorize(CREDENTIALS )
```

**Comment by thomasheuberger** [comment] 2021-07-28 05:50
I've got the same problem here. Have you ever found a fix for this @nissankarkifm ?

**Comment by nissankarkifm** [comment] 2021-07-28 07:25
No, nothing yet. The solution above your comment worked for cloud function but not on compute engine.

**Comment by bolerodan** [comment] 2022-01-27 19:32
Just started to struggle with this. I assume this has not been resolved? Same thing happens if I use `google-api-python-client` discovery directly instead of gspread.

The default service account on GCE instance just doesnt work, but supplying that service accounts JSON key, does work like mentioned above, so what gives?

I plan to have this run on Cloud Run but this totally blocks ever accessing gsheets API

**Comment by thomasheuberger** [comment] 2022-01-28 07:16
@bolerodan What blocks you from using that on Cloud Run? You can always do something like 
`del_cred = Credentials.from_service_account_info(
    credentials,
    scopes=['https://www.googleapis.com/auth/spreadsheets',
            'https://www.googleapis.com/auth/drive'],
    subject="***@***.com")
delegate_gc = gspread.authorize(del_cred)`

We've been using that in production for months

where you pass in the credentials from whatever secure store you chose (like Google Secret Manager or whatever)

**Comment by lavigne958** [comment] 2022-01-28 07:32
Hi to go around that issue in the latest release of gspread we have a new method:
 `def​ ​service_account_from_dict​(​info​, ​scopes​=​DEFAULT_SCOPES​)` 
It allows you to pass your service account credentials manually as a python dict. Instead of the JSON file.

This way you can store your creds where ever you like and don't need to rely an a actual file stored on the local file system.

**Comment by bolerodan** [comment] 2022-01-28 13:40
@thomasheuberger 

Our main reason is to not rely on JSON keys at all, or having to store them in any kind of secret manager.

Google definitely pushes away from json keys as best practices and relies on using attached services accounts on resources where possible

https://cloud.google.com/iam/docs/best-practices-for-using-and-managing-service-accounts#using_service_accounts

For example all of our code relies on the attached service account whether it is on cloud run, or GCE etc, so we never have to manually pass in credentials through a JSON key (by retrieving through a secret store manager) etc. The application code itself just agnostic and we primarily only need to call for example
`creds,project = google.auth.default()` in our code for accessing things like google buckets, pubsub etc.

But I dont think this is an issue specific to Gspread. I get this same issues even when using `google-api-python-client` and using the discovery method to build access to the v4 spreadhseets. 

So I may have to bite the bullet and rely on a key. Wondering if this is more of a bug with googles service account auth.

**Comment by lavigne958** [comment] 2022-01-28 13:48
Hi @bolerodan if you only need to run `creds,project = google.auth.default()` to authenticate to google services, then you can use these credentials you just got and pass them to gspread. you'll be authenticated and will be able to reach your SpreadSheets.

**Comment by bolerodan** [comment] 2022-01-28 13:53
@lavigne958 so atm i'm testing this on GCE (not cloud run / cloud function atm) and using `creds,project = google.auth.default()` provides me with a scope error

```
gspread.exceptions.APIError: {'errors': [{'domain': 'global', 'reason': 'insufficientPermissions', 'message': 'Insufficient Permission: Request had insufficient authentication scopes.'}], 'code': 403, 'message': 'Insufficient Permission: Request had insufficient authentication scopes.'}
```

but manually passing in the service accounts ( that is attached to that VM (or where ever it will run on), hence wanting to use auth.default) JSON key,
```
gspread.service_account(filename="SERVICE_ACCOUNT_KEY.json")
``` 

Works, so im at a loss.

**Comment by lavigne958** [comment] 2022-01-28 14:06
`insufficient authentication scopes` sounds like you need to pass the scopes to your `auth` requests. In GSpread we pass the scopes we need which you can find here: https://github.com/burnash/gspread/blob/75fa419e381add5e2e808864ce161f81c217b831/gspread/auth.py#L18-L21 and pass them to `google.auth.default()`. that might help :-) 

or import them using something like `from gspread.auth import DEFAULT_SCOPES`.

**Comment by bolerodan** [comment] 2022-01-28 14:23
@lavigne958 

My apologies I should have been more exact with my code, I definitely am.

```
import gspread
import google.auth

scopes = [
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive'
]

credentials, project = google.auth.default(scopes=scopes)
gc = gspread.authorize(credentials)
```

**Comment by lavigne958** [comment] 2022-01-28 14:25
Oh ok, then sorry I can't provide much help my knowledges has its limits unfortunately. 

I will close this issue as GSpread can accept a file or a dict as credentials to authenticate.
Any is ver welcome to participate and help solving that issue using this issue thread.

**Closed by lavigne958** 2022-01-28 14:25 UTC

**Comment by bolerodan** [comment] 2022-01-28 14:28
@lavigne958  Thanks for your time!

**Comment by get2prab** [comment] 2022-10-25 07:41
@niczky12 @bolerodan,

Hello, I am facing the same issue. Have you guys found any workaround for this one?

**Comment by PCichowczyc** [comment] 2022-12-21 11:01
Hi, 

I know this is quite an old thread but I was also looking for a solution for a long time.

In my case it helped to add additional scopes for VM :

gcloud compute instances set-service-account INSTANCE_NAME --scopes=cloud-platform,https://www.googleapis.com/auth/drive --service-account=SERVICE_ACCOUNT_EMAIL --zone=ZONE

Of course, in scopes you also need to specify others that you want to have. After this operation, the problem of insufficient permissions disappeared. I hope it can help someone.

Best

**Comment by lavigne958** [comment] 2023-06-30 19:30
@alifeee  I found this https://googleapis.dev/python/google-auth/latest/index.html

It seems in fact that we need to look into the google auth package and we should be able to find some way to connect to a spreadsheet when running inside a google cloud engine :eyes: :thinking: 

If we provide the right function in `gspread/auth.py` it can return some `Credentials` object and be used to make HTTP requests possibly !

**Comment by alifeee** [comment] 2023-07-04 17:38
I'm not sure what the issue is here.

We would like to add a function which does not take a filepath or a json object, which gets the credentials from the Compute Engine?

**Comment by lavigne958** [comment] 2023-07-05 14:55
> I'm not sure what the issue is here.
> 
> We would like to add a function which does not take a filepath or a json object, which gets the credentials from the Compute Engine?

Almost, we would create a new function alongside the existing one like `gspread.service_account()` but this time the given arguments would be some user name etc and we pass that to the Google library that can authenticate against google API when running inside a Google compute engine.

**Comment by alifeee** [comment] 2023-07-06 13:58
sounds good to me. we could reopen this and attempt it.

**Comment by lavigne958** [comment] 2023-07-06 14:48
I would recommend we asses the situation first, try the other `Credential` classes I found in the link above and check if they work etc. if so we can open the issue and make some PRs if not... at least we tried

**Comment by jeffbryner** [comment] 2023-12-13 16:52
for anyone stumbling on this like I did, it's covered here: https://github.com/googleapis/google-auth-library-python/issues/1211 as apparently by design. 

My workaround: 

```
import google.auth
import google.auth.transport.requests
SCOPES = []
credentials, project = google.auth.default(scopes=SCOPES)
google_request = google.auth.transport.requests.Request()
credentials.refresh(google_request)
logger.debug(f"CREDENTIAL EMAIL: {credentials.service_account_email}")

**Comment by thoughtfuldata** [comment] 2024-03-16 04:10
@jeffbryner How would this work with local Application Default Credentials(ADC) during development? ( i.e gcloud auth application-default login). I get "google.oauth2.credentials.Credentials"  for the type

**Comment by jeffbryner** [comment] 2024-03-16 20:48
the default auth should work fine everywhere except a google compute engine
environment like cloud run.

**Comment by arsanysamuel** [comment] 2025-11-04 13:46
Is there any intention to reopen this one day?
It would be nice to be able to use the default credentials both on local environment and cloud.
I'm facing the situation where I have to create a service account for a Cloud Run service, generate a json key file for it, store the content in a secrets manager, recreate the file in the environment using the file content stored in the secrets and then use it with gspread.
This seems inconvenient and doesn't follow the cloud permissions design in my opinion, a cloud service should simply use a designated service account to authenticate get the needed permissions, if a keyfile has to be used then what a service account is for?
Let me know what do you think of this. Thank you
