### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'text'

### ISSUE THREAD

**Issue by rzavadski-ms** [burnash/gspread#1163] opened 2023-01-30 17:37 UTC
---

**Describe the bug**

**To Reproduce**
I am getting this error when gspread raise APIError. I checked the latest version of the package, and nothing has changed in the implementation of the APIError.
```
APIError({'code': 429, 'message': "Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:*'.", 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'quota_location': 'global', 'quota_metric': 'sheets.googleapis.com/read_requests', 'quota_limit_value': '100', 'service': 'sheets.googleapis.com', 'quota_limit': 'ReadRequestsPerMinutePerUser', 'consumer': 'projects}}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Request a higher quota limit.', 'url': 'https://cloud.google.com/docs/quota#requesting_higher_quota'}]}]})
```

**Environment info:**
- Operating System macOS:
- Python version 3.7
- gspread version 5.4.0
- docker version: Docker version 20.10.20, build 9fdeb9c

```
app_admin_celery_tasks-1  |   File "/usr/local/lib/python3.7/site-packages/gspread/exceptions.py", line 41, in __init__
app_admin_celery_tasks-1  |     super().__init__(self._extract_text(response))
app_admin_celery_tasks-1  |   File "/usr/local/lib/python3.7/site-packages/gspread/exceptions.py", line 45, in _extract_text
app_admin_celery_tasks-1  |     return self._text_from_detail(response) or response.text
app_admin_celery_tasks-1  | AttributeError: 'dict' object has no attribute 'text'
```

**Comment by lavigne958** [comment] 2023-02-02 19:27
Hi I checked your issue, I tried to read data in loop from a spreadsheet and nothing particular happens, I get the same `APIError` because I reach the limit of my quota but appart from that I don't have the issue with the `AttributeError: 'dict' object has no attribute 'text'`

I'm sorry but I can't reproduce your issue.

I have not seen any issue with this part of the code, it is triggered every time someone encounters an API error which could happen very often to a lot of people. So I believe that's an issue with your account or your code.

Closing this issue, feel free to comment here if you find more details about it.

**Closed by lavigne958** 2023-02-02 19:27 UTC

**Comment by rzavadski-ms** [comment] 2023-02-02 19:32
> Hi I checked your issue, I tried to read data in loop from a spreadsheet and nothing particular happens, I get the same `APIError` because I reach the limit of my quota but appart from that I don't have the issue with the `AttributeError: 'dict' object has no attribute 'text'`
> 
> I'm sorry but I can't reproduce your issue.
> 
> I have not seen any issue with this part of the code, it is triggered every time someone encounters an API error which could happen very often to a lot of people. So I believe that's an issue with your account or your code.
> 
> Closing this issue, feel free to comment here if you find more details about it.

Thanks for your answer, I'll try to reproduce in with my code and check what happens
