### ISSUE TITLE
Feature Request: Allow user to open unowned 'Anyone can edit' sheets

### ISSUE THREAD

**Issue by edwardotis** [burnash/gspread#145] opened 2014-07-20 23:01 UTC
We share docs with 'anyone with the link can edit' permissions.
If team member A shares a doc with these permission to team member B, gspread is unable to access the doc.

This is a very important restriction and distinction from using the base gdata python client. It's a deal breaker for our organization unfortunately. 

The bug is that this restriction is not in the gspread documentation. I built unit tests and had to look in the implementation to find out about this restriction. It should clearly stated in the interface and documentation.

**Comment by msuozzo** [comment] 2015-10-11 05:03
Confirmed. This needs to be fixed.

**Comment by msuozzo** [comment] 2015-10-11 17:31
Alright so it definitely looks like this is possible. I'm gonna brain dump so the implementation can be discussed because it's non-obvious (at least to me).

I've confirmed that one can access a shared sheet using the normal 'private' visibility and 'full' projection.
* When the sheet is shared as 'Can edit', everything works as normal. Updates can be made, worksheets can be created, etc.
* When the sheet is shared as 'Can View', updates cause 403 errors.

To me, this behavior necessitates some method for the user to determine whether they can update the sheet in question. Some options:
* We could add a spreadsheet property `is_read_only` or some such and make a no-op update. If the update succeeds, False. Else, True.
* Alternatively, we could add `is_read_only` argument to the `Spreadsheet` constructor. This would pass the onus of determining the spreadsheet state to the caller. There are a few ways I think this could be accomplished:
  * Change the signature of `open_by_key` to add an optional `is_read_only` field dictating whether the caller expects to be able to write to the spreadsheet.
  * Add the no-op update check to `open_by_key` and pass the result as the `is_read_only` parameter.

I'm inclined to defer to @burnash on this one as the design choice has the potential to cause an increase in interface complexity.

One last consequence of accessing an unowned spreadsheet (noted by @edwardotis) is that it will not appear in `Client.get_spreadsheets_feed`. So, regardless of the read_only design choice, the `Spreadsheet` constructor will likely need to be refactored as the XML structure it expects is not available with the unowned spreadsheet.

PRs are especially welcome on this one ;)

**Comment by lavigne958** [comment] 2021-05-05 19:09
Tested it on latest version of gspread. Works fine. Access a spreadsheet using the link with only acces "Anyone with the link" and edit access, could edit the spread sheet and get the values. Changed to "viewer only" could not edit the value anymore.

Closing this issue.

**Closed by lavigne958** 2021-05-05 19:09 UTC
Labels: Feature Request

**Comment by hraftery** [comment] 2025-03-08 23:23
For those new to `gspread`, like me, the minimum starting point is not obvious. Here it is for posterity:

```
import gspread

# You still need a service account, but it doesn't need any permissions! Follow the instructions to
# create one: https://docs.gspread.org/en/v5.7.0/oauth2.html#enable-api-access-for-a-project
# The trickiest part is ignoring the thousand things that don't matter. Do only as instructed.
# Neither the "project" or the service account needs any explicit permissions. In particular,
# Step 6, which shares the spreadsheet with the account, is not necessary.
gc = gspread.service_account()
sht = gc.open_by_url(SPREADSHEET_URL)
print(sht.sheet1.get('A1'))
```

**Comment by alifeee** [comment] 2025-03-11 14:16
thanks @hraftery !

is there anywhere in the documentation that you feel this would be helpful ? it would be great if we could put it somewhere :]

**Comment by hraftery** [comment] 2025-03-12 00:33
Hmm, it could possibly go in [Basic Usage](https://github.com/burnash/gspread?tab=readme-ov-file#basic-usage). The heart of the confusion for me was what happens between `import gspread` and `gc.open()`. Do I need a `gc`? Do I need a service account? What are the alternatives and how do I choose? Without those basics, I wasn't sure how to patch stuff together.

It's always hard to put yourself in the mind of a beginner and that moment is so fleeting, but I think it might nearly be enough if the `gc = gspread.service_account()` line has a comment above it like:

```
# To open a sheet, you need access to the Google API. Based on the route you
# chose in Step 1, call either service_account(), oauth() or api_key().
```

And then in [Authentication](https://docs.gspread.org/en/latest/oauth2.html) (which despite the URL, is step one) the three options at the top could be made more prominent with something like:

---

To access spreadsheets your application needs to authenticate itself with the Google Sheets API. Choose from the following options.

1. Create an **[API key](https://docs.gspread.org/en/latest/oauth2.html#api-key)** if you’d like to only open public spreadsheets.
1. Create a **[OAuth Client ID](https://docs.gspread.org/en/latest/oauth2.html#oauth-client-id)** if you’d like to access spreadsheets on behalf of end users (including yourself).
    * When your application runs, it will prompt the user to authorize it.
1. Create a **[Service Account](https://docs.gspread.org/en/latest/oauth2.html#service-account)** to access spreadsheets as a standalone bot.
    * Service accounts get their own email address, so can be authorized by sharing the Sheet with the account in the same way it is shared with a person.
    * Service accounts don't need any explicit permissions to access Sheets that are shared to "anyone with the URL".

An API Key is the easiest option, but to access private Sheets you need authorization. To provide that interactively, use an OAuth Client ID. To pre-configure authorization, use a Service Account.

---

I'm not exactly sure of the meaning of "public" so this could be improved further.

**Comment by alifeee** [comment] 2025-03-12 10:30
wonderful ! I like your suggestions - would you like to suggest them in a PR? :]

It would be great to make the heading of the auth page more prominent. Your list does that. Perhaps also a heading like "## Choose your authentication"

p.s., the URL is "oauth2" because this is what the protocol is called..

**Comment by hraftery** [comment] 2025-03-16 05:19
Okay, I've had a crack. I hope this is in keeping with the goals of the project.

https://github.com/burnash/gspread/pull/1546

PS. I thought OAuth2 was only used in one of the auth options. No big deal, it just threw me at first.
