### ISSUE TITLE
spreadsheet.lastUpdateTime throws KeyError exception

### ISSUE THREAD

**Issue by sgrontflix** [burnash/gspread#1185] opened 2023-04-04 23:06 UTC
**Describe the bug**
I tried using the `spreadsheet.lastUpdateTime` property and it throws a `KeyError` exception because it cannot find the `modifiedTime` attribute. I enabled the **Google Sheet API** and the **Google Drive API** and my credentials are correct.

**To reproduce**
1. Create a Google Sheet document
2. Make sure to enable the Google Sheet and the Google Drive APIs from the Google Cloud Console
3. Edit your spreadsheet
4. Try to retrieve the `modifiedTime` attribute using `spreadsheet.lastUpdateTime`

**Expected behavior**
I should be able to retrieve the `modifiedTime` attribute without any errors.

**Code example**
```python
import gspread

spreadsheetId = "<SPREADSHEET_ID>"

client = gspread.service_account(filename="credentials.json")
spreadsheet = client.open_by_key(spreadsheetId)
worksheet = spreadsheet.sheet1
worksheet.update_acell("A1", "a")
last_edit = spreadsheet.lastUpdateTime  # This throws a KeyError exception
```

**Environment info**
- Operating System: _Windows 10_
- Python version: _3.11_
- gspread version: _5.7.2_

**Stack trace or other output that would be helpful**
```
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\gspread\spreadsheet.py", line 71, in lastUpdateTime
    return self._properties["modifiedTime"]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'modifiedTime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python-projects\gsheet-test\test.py", line 9, in <module>
    last_edit = spreadsheet.lastUpdateTime
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gspread\spreadsheet.py", line 75, in lastUpdateTime
    metadata = finditem(
               ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gspread\utils.py", line 133, in finditem
    return next(item for item in seq if func(item))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

**Additional context**
If I use the `google-api-python-client` package, it works as expected without any issues:
```python
from google.oauth2 import service_account
from googleapiclient.discovery import build

# Authenticate
creds = service_account.Credentials.from_service_account_file("credentials.json")
service = build("drive", "v3", credentials=creds)

# Get the last edit time
last_edit = service.files().get(fileId="<SPREADSHEET_ID>", fields="modifiedTime").execute()["modifiedTime"]
```

**Comment by lavigne958** [comment] 2023-04-07 19:15
Hi, I'm sorry I cannot reproduce the issue you face. I tried it using gspread or the pure HTTP API and it works fine.

To me the issue is in the spreadsheet you try to access. Meaning:

- it fails because the attribute `modifiedTime` does not exists when you use `openByKey`.
- that's not a problem when you request it we go and look for it, we query the Drive API to list the files that have the same name and get the modified time
- here it fails again because it seems that the list return either an empty result or a list of file that do not match your file. 

So I think the issue whether your file is named correctly or shared correctly with the account you use to open the it etc.

Cannot reproduce, closing this issue.
Fee free to comment here if you think there is a proper issue with gspread source code.

**Comment by sgrontflix** [comment] 2023-04-07 19:45
Hi. My file is set as public and everything else works as expected. I'm able to read and edit cells without any issues. I also tried getting the spreadsheet's metadata using gspread and modifiedTime is not there. I forgot to mention that I have the exact same issue with createdTime.

**Comment by lavigne958** [comment] 2023-04-07 22:37
Ho ok I see, the issue is that when trying to load the modifiedTime, we list all your files that match that name, or this file is not in your drive so it does appear in the list 😔 I can think of a solution for this but it won't be a quick fix 😐

**Comment by sgrontflix** [comment] 2023-04-07 22:47
So it's an issue with gspread, right? I'm having trouble understanding... If so, I think you should re-open this issue.

**Comment by lavigne958** [comment] 2023-04-08 06:52
Yes it's an issue with gspread. I'll open the issue and rename it.

## Overview

Can't read `modifiedTime` a public spreadsheet

## expected

- when requesting the `modifiedTime`, get it regardless of the shared access to the spreadsheet

## Root cause analysis

- when we open the sheet using key, we don't have the `moeifiedTime` in the properties
- we then list all the files to find it
- if the file is public we won't see it in the list.
- we won't be able to return the `modifiedTime`

**Comment by lavigne958** [comment] 2023-04-08 18:49
I have a potential fox for this issue:
- when a user request a field that is not stored in the spreadsheet API but in the drive API (like `modifiedTime` ) 
- get the properties from the drive API using the object key so we are sure to get the right properties even if the file is not part of the user personal/shared drive 

I'll try it/implement it when I have some free time (hopefully soon)

**Closed** 2023-05-05 06:59 UTC
